### ISSUE TITLE
[Bug] Popup should be hide while scrolling in background

### ISSUE THREAD

**Issue by championshuttler** [mozilla/extension-workshop#116]
### What happened?
Click on either of `CS Script`, `BG script` or User `interface`  in `Anatomy of an Extension` section. and then scroll in the background without closing the popup. Popup would not disappear.

![image](https://user-images.githubusercontent.com/22130317/53353262-55b81000-394a-11e9-9fcb-c96692dfe837.png)

### What did you expect to happen?
The popup should disappear when we are not in anatomy of an extension section.

Let me know If I am not clear enough here.

**Comment by caitmuenster** [comment]
I'm not sure I understand this issue. I see that the popup has an X mark that the user must interact with to close the popup, and if they don't, the popup stays open when you scroll around the page. This is expected behavior.

**Comment by championshuttler** [comment]
Hi @caitmuenster Yes there is X mark to close the popup but it would be nice if it gets auto disappear if we go to another section by scrolling. If its expected behavior then let's close the issue :).

**Comment by caitmuenster** [comment]
Thanks @championshuttler. :)
