### ISSUE TITLE
Reference to "December 2020" as a future date

### ISSUE THREAD

**Issue by mattalexx** [mozilla/extension-workshop#1203]
> ::: note alert Support for extensions using XUL/XPCOM or the Add-on SDK was removed in Firefox 57, released November 2017. As there is no supported version of Firefox enabling these technologies, this page will be removed by December 2020. :::

https://github.com/mozilla/extension-workshop/blob/24cffb7bba02cd7fff561d6c5d693f14d2329d50/src/content/documentation/develop/comparison-with-the-add-on-sdk.md?plain=1#L35

**Comment by rebloor** [comment]
The comparison page is no longer on Extension Workshop.
