### ISSUE TITLE
Update circle config to support cherry-pick style tags

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/extension-workshop#1236]
We are moving to weekly deploys for extension-workshop, so the tag format will be changing to `YYYY.MM.DD`, which works fine for tagging to stage, but if we need to do a cherry-pick style tag name (e.g., `2022.02.17-1-stage`) the current regex rejects that as a valid tag name. It would be good to be able to use that style of tag name where needed, so we should update https://github.com/mozilla/extension-workshop/blob/master/.circleci/config.yml to allow for tags with that format.

**Comment by willdurand** [comment]
I think that is supported in addons-blog (if one needs inspiration).

**Comment by diox** [comment]
I made https://github.com/mozilla/extension-workshop/pull/1250 to update the docs but yeah, we should update the CircleCI config to match addon-blog's.

**Comment by diox** [comment]
`\d` doesn't seem to be supported in bash, gotta use `[0-9]` ...
