### ISSUE TITLE
"Build Extension in 5 Minutes" video links to wrong video on mobile 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#124]
On mobile, the video for "Build an Extension in 5 Minutes" links to an outdated video. It should link to [this video](https://www.youtube.com/watch?v=Q3AQ5D2QFwc&feature=youtu.be).

**Comment by championshuttler** [comment]
Can i work on it @caitmuenster if you are not :)

Thanks

**Comment by caitmuenster** [comment]
Go for it @championshuttler!

**Comment by ioanarusiczki** [comment]
The video on small screens is https://www.youtube.com/watch?v=Q3AQ5D2QFwc
Verified on EW stage and prod - FF66(Android 8.0)
