### ISSUE TITLE
Add a test case to prevent regression with page at `/documentation/publish/site-permission-add-on/`

### ISSUE THREAD

**Issue by willdurand** [mozilla/extension-workshop#1261]
Given [this URL](
https://extensionworkshop.com/documentation/publish/site-permission-add-on/
) is used in FF now, let's add a test case to avoid breaking it and document the fact that there is a link in a FF error message.

See :https://bugzilla.mozilla.org/show_bug.cgi?id=1758598

**Comment by rebloor** [comment]
@willdurand https://extensionworkshop.com/documentation/publish/site-permission-add-on/ is giving me a 404. So looks of the issue you were concerned about hat happened, do know what content should be on this page?

**Comment by willdurand** [comment]
hum, that got removed in https://github.com/mozilla/extension-workshop/issues/1420. cc @diox

**Comment by rebloor** [comment]
@diox Unless I'm miss reading things, the link still seems to be there in line 78 of [MIDIPermissionRequest.cpp](https://searchfox.org/mozilla-central/source/dom/midi/MIDIPermissionRequest.cpp#78)

**Comment by diox** [comment]
Well that's something to fix in mozilla-central source - but the doc had to go, the whole idea of generating site permission add-ons and hosting them was never fully baked and got removed from AMO/Firefox.

**Comment by willdurand** [comment]
right, you are both correct, except the firefox implementation hasn't been removed yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1789718

I think it's safe to close/wontfix this bug.

**Comment by rebloor** [comment]
Thanks @diox and @willdurand for your feedback, give which I'm closing this issue.
