### ISSUE TITLE
Improve CSS for code with link

### ISSUE THREAD

**Issue by Marcono1234** [mozilla/extension-workshop#1272]
### Describe the problem and steps to reproduce it:

Currently when text formatted as code also has a link, the text is a bit difficult to read. This might also depend on the used browser; I have the impression that for Firefox it is more difficult to read than for Chrome / Edge.

Example:
https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/#signing-test-version-listed

Screenshot:
![Firefox code link screenshot](https://user-images.githubusercontent.com/11685886/158877460-12ff6bab-73d2-4136-87ac-a511e0575db8.png)
(Firefox 98.0.1 (64-Bit))

### What happened?

The text is difficult to read, at least when skimming over the page

### What did you expect to happen?

The text should be easier to read; possibly by using a slighly brigher blue color

**Comment by modernfaust** [comment]
I can work on this issue.

**Comment by Marcono1234** [comment]
@modernfaust, it looks like this issue has actually already been fixed. The example page linked above now looks like this:

![Example page screenshot](https://user-images.githubusercontent.com/11685886/213029553-8db2e112-5623-4ada-9ad1-3fe439f8e8a4.png)

I am therefore going to close this issue. Or are you still seeing the dark background color for text formatted as code (as shown in the original screenshot)?
