### ISSUE TITLE
Clarify the methods for installing self hosted extensions

### ISSUE THREAD

**Issue by rebloor** [mozilla/extension-workshop#1280]
Starting from Firefox 100, a website's "install flow" has to meet the new "user activation" requirement Bug 1759737, in particular, see https://bugzilla.mozilla.org/show_bug.cgi?id=1759737#c12 and, for an example of a website that is hitting this new requirement, https://github.com/webcompat/web-bugs/issues/101685#issuecomment-1083039281 .

**Comment by diox** [comment]
That's for `InstallTrigger` API though, which hasn't been (and should never be) documented on extensionworkshop - it's been deprecated for years, before being removed from MDN the documentation said:
>  This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

Websites should just link to the `.xpi`. Maybe https://extensionworkshop.com/documentation/publish/self-distribution/ could be clarified to say that.

**Comment by rebloor** [comment]
@rpl thoughts?

**Comment by rpl** [comment]
>> Websites should just link to the .xpi. Maybe https://extensionworkshop.com/documentation/publish/self-distribution/ could be clarified to say that.
>
> @rpl thoughts?

@rebloor That is basically the goal of this issue: to make sure we mention clearly from the docs included in or linked from https://extensionworkshop.com/documentation/publish/self-distribution/  what are the supported ways to trigger an addon installation from a third party website, even more important now that we need to prepare the extension developers to 3 changes to the addon install flows in Firefox >= 100:

- user activation requirement (required for both InstallTrigger and navigations to the XPI file) [Bug 1759737](https://bugzilla.mozilla.org/show_bug.cgi?id=1759737) is the one that some extension developers may more likely be hitting in the short run, and it is being enforced in Firefox >= 100 (I'm going to provide you some more details about this, in particular some example of how to make sure to trigger the installation through user activation)

- the additional cross-origin checks introduced in [Bug 1755950](https://bugzilla.mozilla.org/show_bug.cgi?id=1755950) are mainly making an existing requirement slightly more strict, most extension developers shouldn't be hitting it (and so we may just mention that there shouldn't be any third party frame between the top level page and the subframe that is going to be triggering the install flow)

- with [Bug 1754441](https://bugzilla.mozilla.org/show_bug.cgi?id=1754441) InstallTrigger is officially entering into a deprecation stage in Firefox 100 but it is not going to be hidden right away (and so it is still going to be available in Firefox 100 but it will be require user activation)
   - even if InstallTrigger is going to be still available in Firefox 100, we want to prepare the extension developers to migrate away from it, especially given that there is a good chance that they may need to adapt their install flow before Firefox 100 will be hitting the release change to meet the user activation requirement. As @mat mentioned, InstallTrigger has always been a non-standard API but it has been around for a long long time, and so even if not officially supported there are still extensions that are being installed from the extension developers website using InstallTrigger.install
