### ISSUE TITLE
"Anatomy of an Extension" graphic doesn't expand

### ISSUE THREAD

**Issue by pwalm** [mozilla/extension-workshop#13]
When scrolling down the page, the "Anatomy of an Extension" graphic does not expand or animate. It just shows the wireframe of the box:
<img width="1228" alt="screen shot 2018-11-29 at 11 51 18 am" src="https://user-images.githubusercontent.com/6797635/49248438-8f6e8e80-f3ce-11e8-93f5-4e84fb47803e.png">

Tested on Firefox Nightly, Safari, and Chrome.

**Comment by muffinresearch** [comment]
Fixed see https://extensionworkshop.allizom.org/#anatomy-of-an-extension
