### ISSUE TITLE
Add dev environment 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#131]
As part of Phase II (which kicked off today), we'd like to add a dev environment so we can review and QA updates before pushing them to staging and production. 

There's no rush but if we could get this set up by April 15, that would be great. 

cc: @bqbn, @muffinresearch

**Comment by bqbn** [comment]
@caitmuenster could you clarify the difference between -dev and -stage environments for this project?

I thought that we set up -stage so that we could review QA updates before they're pushed to -prod. Why in addition to -stage, do we need a -dev environment?

**Comment by caitmuenster** [comment]
Good question. My understanding is -stage is there to check over before pushing to -prod, and -dev would be to review/evaluate before we even get to -stage. 

@lancecummings, am I capturing that correctly? Would love to hear your thoughts.

**Comment by lancecummings** [comment]
@caitmuenster we could definitely use stage for this. I don't think the dev request came from us originally, but from my memory, there was the suggestion that you might need the stage environment to continue reviewing and publishing content on the existing architecture, while we simultaneously work on testing the new architecture on the dev environment.

**Comment by muffinresearch** [comment]
One plus I can see about having a hosted -dev environment it could be used to show pages that aren't published on stage or production. This would make it easier to check content as right now we're reliant on someone who can run the site to take screenshots for anyone who doesn't have the development enviroment running locally.

**Comment by bqbn** [comment]
>  This would make it easier to check content as right now we're reliant on someone who can run the site to take screenshots for anyone who doesn't have the development environment running locally.

I'm trying to understand, why can't the changes be pushed to -stage env so that all team members can see? Is it something in the current workflow that prevent us from doing that?

**Comment by muffinresearch** [comment]
> > This would make it easier to check content as right now we're reliant on someone who can run the site to take screenshots for anyone who doesn't have the development environment running locally.
> 
> I'm trying to understand, why can't the changes be pushed to -stage env so that all team members can see? Is it something in the current workflow that prevent us from doing that?

If we do that, stage won't then be representative of what will be released into production. Which is not ideal.

**Comment by caitmuenster** [comment]
@muffinresearch If we take the content guidelines out of consideration, would you be comfortable with Lance testing new code on -stage? If not, let's set up -dev; I don't think the work we're doing on the content guidelines alone justifies setting up a new environment.

**Comment by muffinresearch** [comment]
> @muffinresearch If we take the content guidelines out of consideration, would you be comfortable with Lance testing new code on -stage? If not, let's set up -dev; I don't think the work we're doing on the content guidelines alone justifies setting up a new environment.

It'll probably depend on whether the new changes will involve unpublished pages whilst they're being worked on. I still need to better understand precisely what is planned.

**Comment by caitmuenster** [comment]
Ok, cool. I'll set up a meeting. :)

**Comment by caitmuenster** [comment]
After discussing with @muffinresearch this morning, the conclusion is that yes, we'd like to add the -dev environment. :) We'd like to keep the code being developed for Phase II on -dev until it's ready to go live, at which point it will be moved to -staging and then pushed to -prod. Stuart requests that -staging matches -prod as much as possible. 

@bqbn, no rush but if you could set this up sometime in the next 2 - 3 weeks, that would be awesome. Thank you!

**Comment by bqbn** [comment]
We currently push `master` to -stage on every commit. If we're gonna have a -dev environment, how does that change the push logic?

I assume that we'll need to push `master` to -dev on every commit. What about -stage and -prod? What criteria/condition should trigger pushing to those envs respectively?

**Comment by bqbn** [comment]
What the [firstlook.firefox.com](https://github.com/mozilla/concepts) project did is that they have a `stage` and a `prod` branch and merging to each branch triggers pushing that branch to its respective environment.

Relevant code example: https://github.com/mozilla/concepts/blob/master/.circleci/config.yml#L42-L56

Not sure we want to use that model or not.

**Comment by muffinresearch** [comment]
@bqbn for simplicity I think commits to master would deploy to both dev and stage but the difference would be that dev would have a different deploy command to enable content that won't be enabled for stage (and prod).

**Comment by bqbn** [comment]
@muffinresearch thx.

@caitmuenster what should the domain name be for the -dev environment? Does `extensionworkshop-dev.allizom.org` work?

**Comment by caitmuenster** [comment]
That looks good to me! Thanks @bqbn!

**Comment by bqbn** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1541663 for the domain name.

**Comment by bqbn** [comment]
https://extensionworkshop-dev.allizom.org/ is up and running.
