### ISSUE TITLE
dead link in docs

### ISSUE THREAD

**Issue by dmiracle** [mozilla/extension-workshop#1323]
Hello, I'm wondering if anyone knows the updated link for `webextensions.in` referenced here https://extensionworkshop.com/documentation/develop/firefox-workflow-overview/

From this line:
https://github.com/mozilla/extension-workshop/blob/dd06a5bc2638b0bd774e122bfc634fd89c97c290/src/content/documentation/develop/firefox-workflow-overview.md?plain=1#L68

**Comment by eih** [comment]
Hi. I've been looking for an alternative instance of webextensions.in too, but looks like there's none. But there's a command line version of the tool: https://www.npmjs.com/package/create-web-ext. It generates the same files/directories.

BTW, you can run your own instance of webextensions.in. The repo is at https://github.com/web-ext-labs/ui-tool. If you intend to do so, you have to make some changes for it to work locally. You must update all packages and remove some redundant ones.

**Comment by dmiracle** [comment]
Thank you!
