### ISSUE TITLE
Extension Developer Newsletter sign up is not working from EW

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#134]
Followup for https://github.com/mozilla/addons-frontend/issues/7696

STR:
1. Load AMO dev or stage and click on Extension Workshop link
2. Scroll down the page until you see Extensions Developer Newsletter
3. Type in an email address and check the Mozilla terms 
4. Click Sign up 

Expected result:
User is directed to this page https://www.mozilla.org/en-US/newsletter/

Actual result:
Nothing happens

Notes:
This issue is only reproducible on Win10 - FF65. It is not reproducible on Android 8.0 

![sign up won't work](https://user-images.githubusercontent.com/33448286/55075810-910a4380-509c-11e9-9223-f55793beae67.gif)

**Comment by ioanarusiczki** [comment]
@muffinresearch I can still reproduce this issue with FF66(Win10).

**Comment by muffinresearch** [comment]
@ioanarusiczki CSP has been updated and deployed to stage - it looks to work as it should now.

**Comment by ioanarusiczki** [comment]
@muffinresearch I went to AMO stage (Win10, FF66) and clicked on EW from the header of the page. Tried to subscribe again but without any success :( 

![nope](https://user-images.githubusercontent.com/33448286/55166238-6d67fb80-5177-11e9-8479-89483e34db08.gif)

**Comment by muffinresearch** [comment]
@ioanarusiczki you're testing on prod, the fix is only on stage.

**Comment by ioanarusiczki** [comment]
@muffinresearch Verified on https://extensionworkshop.allizom.org/ and https://extensionworkshop.com/ with FF66 (Win10 and Android 8.0)
The user is now redirected from the e-mail received to confirm the subscription https://www.mozilla.org/en-US/newsletter/  

![newsletter](https://user-images.githubusercontent.com/33448286/55227507-56c9af00-5220-11e9-962d-b640ce56a6fb.gif)
