### ISSUE TITLE
Extension Workshop page will direct the user on AMO prod, it won't show the dev and stage environment

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#139]
Followup for https://github.com/mozilla/addons-frontend/issues/7696 and https://github.com/mozilla/addons-server/issues/10909

STR:
1. Load AMO dev https://addons-dev.allizom.org/en-US/firefox/ or AMO stage https://addons.allizom.org/en-US/firefox/ 
2. Click on Extension Workshop and login from there
3. Observe the page

Expected result:
Dev Hub dev or stage loads such as https://addons-dev.allizom.org/en-US/developers/addons
or  https://addons-dev.allizom.org/en-US/developers/

Actual result:
User is redirected on AMO prod https://addons.mozilla.org/en-US/developers/

Notes:
The issue is reproducible on AMO dev and AMO stage - FF65 (Win10 & Android 8.0)

![AMO prod](https://user-images.githubusercontent.com/33448286/55074562-4affb080-5099-11e9-9dca-374b18d7c012.gif)

**Comment by muffinresearch** [comment]
There is no -dev environment currently, so the only fix we could have here is to make the EW stage deployment conditionally update it's links to AMO based on the deployment environment.

**Comment by ioanarusiczki** [comment]
@muffinresearch Then https://extensionworkshop.allizom.org/ should work with AMO stage. When registering from stage should land on dev hub stage instead of prod too. 
Would be ideal for testing.

**Comment by muffinresearch** [comment]
@ioanarusiczki this bug is about the login, which is hard-coded to prod AMO. To fix getting to prod EW, or stage EW from AMO would require bugs on addons-server and addons-frontend if we don't have them already.

**Comment by ioanarusiczki** [comment]
@muffinresearch I filed these two https://github.com/mozilla/addons-frontend/issues/7812 
https://github.com/mozilla/addons-server/issues/11099
Should cover it now.

**Comment by rebloor** [comment]
The two related issues created on mozilla /
[addons-frontend](https://github.com/mozilla/addons-frontend) are fixed and include illustration of the correct linking. Also tested and confirmed.
