### ISSUE TITLE
Document how developers can have MV2 and MV3 versions in parallel on AMO

### ISSUE THREAD

**Issue by diox** [mozilla/extension-workshop#1415]
On AMO public listing pages, we currently only display the latest publicly available version for each add-on, whatever that version is. If that version isn't compatible with your browser, we display an error message instead of the install button.

Because MV3 add-ons are not going to be compatible with older versions of Firefox, developers trying out MV3 could end up releasing a version that would make their add-on difficult to install for users.

We need to document on extensionworkshop how they can work around that limitation and still release "beta" MV3 versions of their add-on to early adopters.

The work will likely happen in a google doc first, but this issue is useful to track what we need to do (and we might link it to a Jira ticket too to monitor progress).

**Comment by diox** [comment]
Since we no longer support beta versions on AMO (*), the idea is going to resolve around using the normal AMO channel for your MV2 version, and in parallel the self-hosted distribution channel for your MV3 version while it's still experimental and versions of Firefox supporting MV3 aren't widely used yet. Then at some point, if/when your MV3 version is considered ready for the general public, you can switch over (without forgetting to provide an upgrade path for those on the self-hosted channel).

Some popular add-ons like ublock-origin already do this for their "beta" versions right now.

(*) This might come back in the future, but not in time for this.

**Comment by eviljeff** [comment]
https://docs.google.com/document/d/16LHImKvl6b1IFDpntRn2q_0w3LAgQrbKahPUvCpyyxc/edit is the working doc (needs Mozilla auth to access)

**Comment by diox** [comment]
Will be fixed by https://github.com/mozilla/extension-workshop/pull/1453
