### ISSUE TITLE
The Menu Bar won't display the sections on Android devices

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#142]
STR:
1. Load AMO and click the Extension Workshop link
2. Click on any of the options from the navigation menu bar, such as "Build extensions" or "Developer News"
3.Observe the screen

Expected result:
The section is displayed.

Actual result:
Section appears for a second than the screen jumps to the header of the page.

Notes:
This issue is reproducible on Huawei Media Pad M5, Huawei mate 10 with Android 8.0.
Later edit - Also reproducible on Pixel and Samsung devices with Android 8.0.

![videotogif_2019 03 28_10 59 10](https://user-images.githubusercontent.com/33448286/55146246-dbe39400-514c-11e9-97b8-5a95a702d395.gif)

**Comment by muffinresearch** [comment]
@ioanarusiczki which Firefox version is this, are they the same version for other devices too?

**Comment by ioanarusiczki** [comment]
@muffinresearch It's the last release version for all of them FF 66.0.2

**Comment by ioanarusiczki** [comment]
@muffinresearch I must update this issue as I verified on other Android devices, and I see it reproducible on all with FF 66.0.2 release. It looks like it's a general platform issue. 

This is a Google Pixel android device

![menu issues](https://user-images.githubusercontent.com/33448286/56566444-53c1a480-65bb-11e9-956c-586a8807d1fd.gif)

**Comment by muffinresearch** [comment]
Closing this as it was filed for v1.
