### ISSUE TITLE
[Android] The Jump to menu will not collapse when the device rotates from landscape to portrait mode

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#143]
**STR:**

1. Load the extension workshop on a mobile device
2. Tap on the Jump to option - notice the menu collapsing to reveal additional items
3. Rotate your device in landscape mode
4. Rotate the device back in portrait mode
5. Tap again on Jump to...

**Actual result:**
The menu doesn't collapse anymore

**Expected result:**
The Jump to menu is expanded

**Notes:**
- reproduced on Android 8.0 mobile, with FF66

![2019-03-28_10-48-58](https://user-images.githubusercontent.com/31961530/55146325-059cbb00-514d-11e9-9a92-3bccb421f946.gif)

**Comment by muffinresearch** [comment]
There is no jump menu in the new site design, though this sounds similar to https://github.com/mozilla/extension-workshop/issues/433
