### ISSUE TITLE
Docs of `web-ext sign --id` with existing id suggest nothing will happen

### ISSUE THREAD

**Issue by hymccord** [mozilla/extension-workshop#1432]
### Describe the problem:

In the docs of the `web-ext sign` command, the `--id` parameter ([here](https://github.com/mozilla/extension-workshop/blob/master/src/content/documentation/develop/web-ext-command-reference.md#--id)) states:

> This has no effect if the extension already declares an identifier in its manifest.

However discussion in mozilla/web-ext#2040 (this [comment](https://github.com/mozilla/web-ext/issues/2040#issuecomment-709327816)) says the bug of throwing an error and returning error code 1 is the desired effect and was closed as not a bug.

Should the docs be updated to state that an error will be thrown instead of suggesting that there is "no effect" when an id is specified in both the cli parameter and manifest?  

I am more than willing to PR the change if this is something that needs to be addressed!

**Comment by willdurand** [comment]
`--id` is going to be removed in web-ext v8 fwiw

**Comment by willdurand** [comment]
see #1874
