### ISSUE TITLE
Clicking outside the info text boxes or using "Esc" key won't dismiss them

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#144]
STR:
1. Load EW page and navigate down to Anatomy of an Extension
2. Click on User Interface, Content Scripts or Background Scripts
3. Try to dismiss the info box clicking outside the box or using "Esc" key

Expected result:
The box is no longer displayed.

Actual result:
The box is available until "x" is clicked.

Notes:
This issue is reproducible on Win10 and Android 8.0

![dismiss](https://user-images.githubusercontent.com/33448286/55148323-a5a81380-5150-11e9-8dcd-25cecb5f1f80.gif)

**Comment by muffinresearch** [comment]
Fixed in #262

**Comment by ioanarusiczki** [comment]
@muffinresearch This is fixed on EW dev. - FF68(Win10)
On EW stage it is still reproducible. 

![fixedondev](https://user-images.githubusercontent.com/33448286/63272984-c0b52480-c2a5-11e9-8e6e-5a5494bb5d23.gif)

**Comment by muffinresearch** [comment]
> @muffinresearch This is fixed on EW dev. - FF68(Win10)
> On EW stage it is still reproducible.
> 
> ![fixedondev](https://user-images.githubusercontent.com/33448286/63272984-c0b52480-c2a5-11e9-8e6e-5a5494bb5d23.gif)

Yep, that's fine - stage is not push to automatically.
