### ISSUE TITLE
Add example usecase / link to resources for working with Native Messaging

### ISSUE THREAD

**Issue by abhn** [mozilla/extension-workshop#1468]
### Documentation gap:
We do not have much documentation around native messaging on EW except for the link to the MDN documentation page (on this page https://extensionworkshop.com/documentation/develop/testing-persistent-and-restart-features/). 

### Suggestion
A page explaining extensions that communicate with native apps and explaining (or linking to) some key concepts like the location of the app manifest, and that the app manifest should be shipped with the native app and not the extension etc.

**Comment by Rob--W** [comment]
What would be the value of new content over the existing content at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging ?

**Comment by abhn** [comment]
Upon re-reading the MDN documentation on NativeMessaging, I found the information that I didn't find in EW directly there. Specifically, the part around app manifest, it's location, installation and invocation of the native application are all documented on the MDN page. 

I think this ticket was created because I expected that information to be summarized on EW, which now makes little sense (if only because I know how to find the answers to those questions quicker now). But since I don't have any improvement suggestions here, I'd close this ticket.
