### ISSUE TITLE
Clarification about mv3 required ID and mv2/mv3 addon release management

### ISSUE THREAD

**Issue by wesinator** [mozilla/extension-workshop#1510]
### Describe the problem and steps to reproduce it:

So according to moz addon documentation, [mv3 extensions require an explicit add-on ID](https://extensionworkshop.com/documentation/develop/extensions-and-the-add-on-id/) specified in the [browser_specific_settings key](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#firefox_gecko_properties) (#1310)

Say I have an mv2 version `2.0` of my extension that is mv2 and doesn't have a specified id set (id will be random uuid). 

Then I upload an mv3 version, v3.0 with the required id (a new email-like ID) and strict_min_version setting.

Would these be registered as two separate addons because they don't have the same addon id, and the browser might install both side by side ?

**Proposals:**
 - Add clarification to docs that developers need to add the ID they create for their mv3 addon to their latest mv2 release to make sure that AMO/Firefox knows that it's the same addon

OR

 - Add note that developers need to take the ID of their current mv2 version from devhub and use it for their mv3 addon so that the IDs match

**Comment by wagnerand** [comment]
I am not sure if this needs explicit documentation. AMO will throw an error during update submission if the ID in the manifest does not match the ID of the add-on instance you are submitting the update for.

**Comment by wesinator** [comment]
I understand now - it shows a message when a dev tries to upload a new version with a non-matching ID.
