### ISSUE TITLE
Additional rights

### ISSUE THREAD

**Issue by rebloor** [mozilla/extension-workshop#1528]
I would like to be able to: 

- add reviewers to PRs I create 
- merge PRs I create after approval

**Comment by willdurand** [comment]
@diox could you please look into that?

**Comment by diox** [comment]
Sorry I forgot to reply but I did give @rebloor `Triage` rights over the repos, which I think should be enough here. Let me know if that's not the case.

**Comment by diox** [comment]
Upgrade to `Write` today.

**Comment by rebloor** [comment]
Thanks @diox
