### ISSUE TITLE
Lists of links should be marked up as <ul>

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#156]
The navigation links are just a div full of links. This would be better marked up as a list of links:

![Extension_Workshop___Firefox_Extension_Workshop__Make_the_web_do_what_you_want__If_you_can_dream_it__our_open_souce_API_and_your_HTML__CSS__and_JavaScript_skills_can_make_it_happen_](https://user-images.githubusercontent.com/1514/55548287-0abcb580-56cb-11e9-89e5-2a33a0b63266.jpg)

**Comment by ajinkabeer** [comment]
Hello @muffinresearch, I am outreachy applicant. Can I try this one out please?

**Comment by muffinresearch** [comment]
@ajinkabeer sure, go ahead.

**Comment by ajinkabeer** [comment]
Hey @muffinresearch, thanks for assigning this issue to me. I looked up the whole codebase to find the above code section, but I couldn't. Is it fixed somehow? or the layout has been changed?
Correct me if I am wrong, please!.

**Comment by muffinresearch** [comment]
@ajinkabeer indeeed it looks like this was cleaned up at some point without this bug being closed. On that basis I think this can be closed out.
