### ISSUE TITLE
Policies: clarify the best practices for collecting user data consents

### ISSUE THREAD

**Issue by wesinator** [mozilla/extension-workshop#1575]
### Describe the problem and steps to reproduce it:

The current addons consent best practices have some ambiguity around implementation, specifically:

the addons review team expects consent dialogs to be simple, with all the consents on one page.

### What happened?

The graphics under the ["Your Consent Dialogs" section of current guidance on consents](https://extensionworkshop.com/documentation/develop/best-practices-for-collecting-user-data-consents/#your-consent-dialogs) create some ambiguity around how consents should be contained in one dialog UI. 

![image](https://user-images.githubusercontent.com/5124946/228884618-3274e3ad-56d3-4f20-b9ec-f106d18912c0.png)

![image](https://user-images.githubusercontent.com/5124946/228884567-582af1d8-2558-4d4d-a9bb-e2e181a4b300.png)

### What did you expect to happen?

Update the graphics/mockups under https://extensionworkshop.com/documentation/develop/best-practices-for-collecting-user-data-consents/#your-consent-dialogs to reflect a simple, straightforward consent interface implementation.

**Comment by rebloor** [comment]
@wesinator do you have any more specific information about what constitutes a "reflect a simple, straightforward consent interface implementation"

**Comment by wagnerand** [comment]
We are looking into this from a more holistic point of view to see what other changes we need to make in the best practices. When we are ready, we'll file a new issue.
