### ISSUE TITLE
.tiles-container::after has 100vw width, which results in a bottom horizontal scrollbar on the homepage

### ISSUE THREAD

**Issue by aesqe** [mozilla/extension-workshop#172]
### Describe the problem and steps to reproduce it:

Visit the Extension workshop homepage, notice the bottom horizontal scrollbar.

It's visible in FF 66.0.3 and Chrome 73.0.3683.103 on Windows

### What happened?

A horizontal bottom scrollbar is visible.

### What did you expect to happen?

A horizontal bottom scrollbar is not visible.

### Anything else we should know?

I'm not familiar with the codebase, but two quick fixes for this are:
```css
.section-tiles {
  overflow: hidden;
}
```
or changing the `100vw` [on this line](https://github.com/mozilla/extension-workshop/blob/master/_assets/css/_landing.scss#L487) to `100%`

**Comment by muffinresearch** [comment]
@AlexandraMoga would it be possible re-validate if this is an issue with the newer design?

**Comment by rebloor** [comment]
There is no horizontal scroll bar visible on the site, either in Firefox or Chrome.
![image](https://github.com/mozilla/extension-workshop/assets/7352080/e22d66ca-2db2-464b-9487-27f0379de414)
