### ISSUE TITLE
Minor text update

### ISSUE THREAD

**Issue by esullivan-moz** [mozilla/extension-workshop#1736]
Under the section heading "Effect on your add-on UI", on [this page](https://extensionworkshop.com/documentation/develop/differences-between-desktop-and-android-extensions/), there is a sentence that requires updating.

The sentence in question is:

"You cannot reveal your add-on through a sidebar or context menu. However, you can expose your extension as an option under the Add-ons item in the browser menu **or as an address bar button**."

This part of the sentence is no longer accurate and needs to be removed, "...**or as an address bar button**"

I vetted this with the Android Engineering team (Rob W)

**Comment by abitrolly** [comment]
So the compatibility page need to be updated then https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/page_action#browser_compatibility

**Comment by esullivan-moz** [comment]
yes.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs
