### ISSUE TITLE
js bundle is a 404

### ISSUE THREAD

**Issue by eviljeff** [mozilla/extension-workshop#1812]
https://extensionworkshop-dev.allizom.org/assets/js/bundle.f8730e1d.js is a 404, leading to some functionality being broken (visually, on pages that have a LHS navigation bar, such as https://extensionworkshop-dev.allizom.org/documentation/develop/, it's missing)

I noticed this on EW stage, but a pushing the same tag (with a new name) succeeded, which possibly means it's intermittent.

**Comment by willdurand** [comment]
I cannot reproduce anymore, I double-checked the URL above after each commit I landed lately. Closing for now...

**Comment by eviljeff** [comment]
I'd be tempted to say the postcss update you merged fixed this, rather than it randomly now not being reproducible, but either way 👍
