### ISSUE TITLE
NoSuchKey error is returned for URLs without a trailing slash `/`

### ISSUE THREAD

**Issue by abhn** [mozilla/extension-workshop#1894]
### Describe the problem and steps to reproduce it:

EW pages only work when the trailing slash is added. When there isn't one (For example, https://extensionworkshop.com/documentation/publish/third-party-library-usage) the visitor gets an error message (See picture)

<img width="834" alt="image" src="https://github.com/mozilla/extension-workshop/assets/6270406/f0b3a967-038c-4dbc-9085-570d03c7834e">

Potentially related https://github.com/mozilla/extension-workshop/issues/1835

### What did you expect to happen?
Even if the slash isn't added by a user (say, because they edited it, or copied partially without the trailing slash), we should redirect to the right page (with the slash)

### Anything else
I can reproduce this on many (all I tested) EW pages
https://extensionworkshop.com/documentation/publish/source-code-submission
https://extensionworkshop.com/documentation/develop/best-practices-for-collecting-user-data-consents
etc

**Comment by pattersonbl2** [comment]
This issue should be resolved with a infra changes.

**Comment by willdurand** [comment]
(see: https://github.com/mozilla-it/webservices-infra/pull/2234a)
