### ISSUE TITLE
Dev environment is not using the unpublished flag.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#191]
The development environment should be showing the unpublished content whereas stage should not. As it stands neither env is showing the unpublished content. 

To do that the build needs to be passed an `--unpublished` flag only for the **dev** build.

See https://jekyllrb.com/docs/configuration/options/#build-command-options

**Comment by muffinresearch** [comment]
Right now the stage and dev deploys are all being pushed up from the same build, so this needs updating.

**Comment by bqbn** [comment]
Fixed by https://github.com/mozilla/extension-workshop/pull/201.
