### ISSUE TITLE
Allow for deploying a specific tag to stage without deploying that tag to prod.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#192]
In case we need to bugfix when work is in progress, it would be helpful to add the facility for a specific tag to be pushed to stage in-case we need to stage a specific tag ahead of pushing it to production.

**Comment by muffinresearch** [comment]
Perhaps we can add a `-stage` suffix to a tag which would indicate this should be deployed to stage, at this point we could also stop publishing to stage on commits to master and **only** publish to stage when a tag has a `-stage` suffix. 

Naturally a tag with a `-stage` suffix should **not** be published to production.

**Comment by bqbn** [comment]
I'm OK with this method. One other project (https://github.com/mozilla/concepts) has 3 branches, "master", "stage" and "prod" that track dev, stage and prod respectively.

I think we can try this first and make adjustment if needed.
