### ISSUE TITLE
Sidebar headings get hidden with a long side-bar upon navigation.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#209]
Having navigated to `/documentation/develop/` click on a page low down in the left-hand scroll-bar.

See the following: 

<img width="1847" alt="Build_a_secure_extension___Extension_Workshop" src="https://user-images.githubusercontent.com/1514/61074836-85a31400-a410-11e9-8924-f2a373dd50f1.png">

This example is not the worst case - it is possible for the side-bar high-lighted nav to be hidden completely.

There is also no bread-crumb navigation indicating where you are in the current hierarchy it just refers to `develop`, so the relationship between the current page and the other pages is not clear.

<img width="1847" alt="Build_a_secure_extension___Extension_Workshop" src="https://user-images.githubusercontent.com/1514/61075399-d109f200-a411-11e9-9c96-3f4e4e6fd404.png">

As a fix it would be good to consider:

* Limiting the side-bar to reflect the current place in the content hierarchy (e.g. having navigated to `/develop/build-a-secure-extension/` only the pages under the heading `User Experience` should be shown, ideally this would be accompanied with a breadcrumb update showing `Develop -> User Experience` to make it clear how to get back.
* The side-bar could be some kind of accordion that only shows the content under one sidebar heading at once but allowing opening the others. In the case above the content under `User Experience` would be visible but everywhere else would only show the headings. This still might have issues with enough content and a small enough viewport.

**Comment by caitmuenster** [comment]
It looks like we won't have the resources to address this within our current contract, so in lieu of an engineering solution I am ok'ing addressing this via content setup in the markdown files. 

To give an indication of the sub-topic, we can show topic + sub-topic in the in the markdown file in the `topic` and `h1` fields. 

Example: 

Topic: Develop > User Experience
h1: Build a secure extension
