### ISSUE TITLE
Code does not wrap and breaks sidenav  

### ISSUE THREAD

**Issue by andrewtruongmoz** [mozilla/extension-workshop#217]
### Describe the problem and steps to reproduce it:

When attempting to display a large amount of code in one line, the text does not wrap.

Example: the bad code example located at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Source_Code_Submission#Use_of_obfuscated_code 

### What happened?

Code example stretched along the page and subsequently broke the sidenav. 

### What did you expect to happen?

Code example to display in a box wrapped and navigation to still work. 

### Anything else we should know?

![image](https://user-images.githubusercontent.com/28877053/61731276-fd860e00-ad2f-11e9-9718-963e0fd4bec0.png)

**Comment by lancecummings** [comment]
Fix provided in pull request #218

**Comment by andrewtruongmoz** [comment]
As mentioned on Slack, with this fix, when text is wrapped, the position of the line number is shifted to the left when compared to a smaller code example where the text isn't wrapped. 

<img width="936" alt="Screen Shot 2019-07-25 at 4 23 19 PM" src="https://user-images.githubusercontent.com/28877053/61915476-71274700-aef9-11e9-870d-9bf3ef40bad4.png">
