### ISSUE TITLE
Scrolling issue in the 'Documentation' pages when using the left side panel navigation to reach the first listed topic

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#219]
### Describe the problem and steps to reproduce it:

1. Go to https://extensionworkshop-dev.allizom.org/documentation/develop/
2. Click on User Experience in the navigation menu from the left side panel
3. Click on Firefox Tools to return to the first topic

### What happened?
The page doesn't scroll up fully and the "Firefox Tools" title is overlapped by the header menu

### What did you expect to happen?
The page should scroll up further to expose the entire section title

### Anything else we should know?
- the same issue will reproduce in all other "Documentation" pages, when using the left side panel navigation to return to the first listed topic
- reproduced with Fx68, Win10x64

![2019-07-25_12-03-02](https://user-images.githubusercontent.com/31961530/61862053-dec17c00-aed5-11e9-8490-6fb0cd93f890.gif)

**Comment by caitmuenster** [comment]
@lancecummings, could you look into this?

**Comment by muffinresearch** [comment]
Looks like this was fixed in #260

**Comment by AlexandraMoga** [comment]
Verified fixed:

![2019-08-19_14-13-41](https://user-images.githubusercontent.com/31961530/63261244-ab330100-c28b-11e9-8810-9b01d0307632.gif)
