### ISSUE TITLE
Cards and links remain highlighted/underlinded

### ISSUE THREAD

**Issue by acornestean** [mozilla/extension-workshop#221]
### Describe the problem and steps to reproduce it:
Cards and links from the EW page remain highlighted/underlined after clicking on them. Clicking outside them will clear the highlights.

Steps to reproduce:
1. Load the EW page
2. Click on several cards and links from the EW page
3. As most links and cards redirect the user to another page, return to the EW page
4. Notice that the previously clicked on cards and links remain highlighted/underlined until clicking outside them.

### What happened?
Highlights remain upon returning to the EW page and are cleared only after clicking outside the cards/links area.

### What did you expect to happen?
The highlights should clear upon returning to the EW page.

### Anything else we should know?
The issue occurs on macOS 10.13.6 and Windows 10 Pro 64-bit.

![Card and link highlights remain present](https://user-images.githubusercontent.com/50236075/61870565-184eb300-aee7-11e9-9604-b2ea5e0d56b3.gif)

**Comment by muffinresearch** [comment]
That's expected as this is a focus style too. Clicking a link focuses it. It's still focused when coming back to the page.
