### ISSUE TITLE
Search terms remain in the search box upon cancelling the process

### ISSUE THREAD

**Issue by acornestean** [mozilla/extension-workshop#226]
### Describe the problem and steps to reproduce it:
Search terms remain in the search box upon cancelling the search process (by means of the X button at the end of the field) and clicking on the Magnifying Glass button once more.

Steps to reproduce:
1. Load the EW page
2. At the top of the page, click on the Magnifying Glass icon (a search box will be displayed)
3. Enter any term in the search box
4. Cancel the search process via the X button at the end of the search box
5. Click on the Magnifying Glass icon once more
6. Notice that the previously input search term is still displayed in the search box

### What happened?
Terms remain displayed in the search box after cancelling the process.

### What did you expect to happen?
Any input terms should clear from the search box once the search process has been cancelled.

### Anything else we should know?
The issue occurs on macOS 10.13.6 and Windows 10 Pro 64-bit.

![Terms remain in search box](https://user-images.githubusercontent.com/50236075/61878949-b26c2680-aefa-11e9-888c-56daa1477af5.gif)

**Comment by caitmuenster** [comment]
@muffinresearch / @lancecummings, is this expected behavior?

**Comment by muffinresearch** [comment]
I don't think it's a huge problem. The cross is closing the search box, not clearing the content of the field. It could do both though.

**Comment by caitmuenster** [comment]
Agreed; I think this is a nice-to-have but not a huge priority.
