### ISSUE TITLE
Add links to Extension Basics Screen

### ISSUE THREAD

**Issue by jpfaller** [mozilla/extension-workshop#229]
On https://extensionworkshop-dev.allizom.org/extension-basics/, under Getting started, let's add links to the bullets in order to allow users to access deeper pages.

Tools and processes for developing and testing - LINK TO DEVELOP
How to publish your extension on addons.mozilla.org or distribute it yourself. - LINK TO PUBLISH
How to manage your published extension - LINK TO MANAGE
An enterprise guide for developing and using extensions  - LINK TO ENTERPRISE
How to develop themes for Firefox - LINK TO THEMES
Firefox developer communities - LINK TO COMMUNITY

**Comment by AlexandraMoga** [comment]
On the same page, should't the options under Mozilla Developer Network also be linked ?

**Comment by caitmuenster** [comment]
Yes, we should also link out to `https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions`.

**Comment by championshuttler** [comment]
cc @ruchikabgosain

**Comment by ruchikabgosain** [comment]
Thankyou @championshuttler, working on this!
