### ISSUE TITLE
Order of sections on Manage Page

### ISSUE THREAD

**Issue by jpfaller** [mozilla/extension-workshop#231]
Can we move the whole "Promote Your Extension" section further down the page, so it is in between "Manage authors..." and "Removing your extension" sections.

**Comment by jpfaller** [comment]
This appears on https://extensionworkshop-dev.allizom.org/documentation/manage/

**Comment by ruchikabgosain** [comment]
Hello @caitmuenster, is this issue still open? Would love to take this up!

**Comment by caitmuenster** [comment]
@ruchikabgosain This is still open! Happy bug fixing!
