### ISSUE TITLE
Section Title on Enterprise page

### ISSUE THREAD

**Issue by jpfaller** [mozilla/extension-workshop#232]
The first H2 says "Section Title" is this component required, or can we remove it and just start with body copy.

**Comment by jpfaller** [comment]
https://extensionworkshop-dev.allizom.org/documentation/enterprise/

**Comment by ruchikabgosain** [comment]
Hey @caitmuenster, let me know if I can take up this issue and which files would I need to edit exactly? 

Thanks ♥️

**Comment by caitmuenster** [comment]
Hey @ruchikabgosain, this one's yours! This one is in the `pages.yaml file` in the  `_data folder`. I don't think you need to make any changes to the `enterprise.md` file but you might want to double check it when you're testing it locally.

**Comment by championshuttler** [comment]
@caitmuenster looks like wrong text used in PR, we are good to close this issue .

**Comment by caitmuenster** [comment]
Closed by #329 .
