### ISSUE TITLE
Section Titles on Themes pages

### ISSUE THREAD

**Issue by jpfaller** [mozilla/extension-workshop#233]
On the Themes page, What themes are and Creating themes are not in the content matrix. Are these required elements?

If not, can we kill "What themes are" and replace "Creating themes" with

How to create themes

**Comment by muffinresearch** [comment]
@jpfaller thanks very much for the bug reports. 

If you could provide links to the relevant pages on -dev (https://extensionworkshop-dev.allizom.org/) that will help us pin down precisely what content needs to be updated.

**Comment by jpfaller** [comment]
@muffinresearch Yep! Sorry, this content appears on https://extensionworkshop-dev.allizom.org/documentation/themes/

**Comment by caitmuenster** [comment]
Thanks @jpfaller -- apologies for not including this in the content matrix! 

I'm consolidating the themes overview section by 1) moving a condensed "what themes are" blurb into the header and 2) making the rest of the overview page solely about creating themes.
