### ISSUE TITLE
"Get involved in the community" section contains links to restricted documents

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#237]
**Prerequisites** - before you follow the below steps, make sure that you are not logged into your mozilla account

### Describe the problem and steps to reproduce it:

1. Access https://extensionworkshop-dev.allizom.org/community/#get-involved-in-the-community
2. Click on the [visit the Contribute page](https://docs.google.com/document/d/1_fRGPgjNF3jX-xEROosUx0jmu6PwCY4UNC42EOoHfKQ/edit) link

### What happened?
You are asked to log in in order to view the requested document. If you log in with a non-mozilla account, you are asked to request access in order to view the document contents.

### What did you expect to happen?
Since this information is public, we need to make sure that those documents don't have restricted access

### Anything else we should know?
- the same issue happens with [Mozilla’s goals for the API](https://docs.google.com/document/d/10DoLNszOr94pKV6I1KNC7OYHdMn5TqDP7W6rBju1LEs/edit) document
@caitmuenster if this is the expected behavior before the extension workshop goes live, then this bug can be ignored, or simply kept as a reminder to make the mentioned documents public

![2019-07-26_11-21-22](https://user-images.githubusercontent.com/31961530/61937483-a2565480-af97-11e9-90fe-1222f1a75e8d.gif)

**Comment by caitmuenster** [comment]
Thanks @AlexandraMoga! Those Google doc pages contain the content to be transferred onto the site -- we'll need to build these pages out and change the link before this goes live.

**Comment by ruchikabgosain** [comment]
Hey @caitmuenster, we changed the Google Drive links to those pages in the bugs recently. I believe this issue should be done? 🤔

**Comment by caitmuenster** [comment]
Hey @ruchikabgosain, not quite yet. 

"Goals for the API" should link to `/documentation/develop/about-the-webextensions-api/`

The "contribute" page still needs to be built (it's on my to-do list).

**Comment by ruchikabgosain** [comment]
Ah! Alrighty @caitmuenster. Is there a bug for "Goals for API" or a way for me to fix that? Would love to do that 🙇✨

**Comment by championshuttler** [comment]
@ruchikabgosain  yes i guess https://github.com/mozilla/extension-workshop/blob/518b1026a6f6dde95c7004db08250ba44aa2a582/community.md#L94 should be linked to 
`/documentation/develop/about-the-webextensions-api/`

**Comment by ruchikabgosain** [comment]
Right, thanks, on it @championshuttler 🙇

**Comment by caitmuenster** [comment]
This should be closed by #330 and #338.

**Comment by AlexandraMoga** [comment]
I see that the name of the links have changed a bit, but they are now redirecting to their corresponding resources.
