### ISSUE TITLE
Users should also have the option to collapse an expanded section from the side panel 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#238]
### Describe the problem and steps to reproduce it:

1. Open https://extensionworkshop-dev.allizom.org/documentation/develop/
2. Click on [Browser Extension Development Tools](https://extensionworkshop-dev.allizom.org/documentation/develop/browser-extension-development-tools/)
3. Observe that the section expands
4. Click again on the parent folder

### What happened?
The section remains expanded

### What did you expect to happen?
The section should collapse if the parent folder is clicked again

### Anything else we should know?
- this issue is valid for all the sections with submenus
- reproduced on FX68, Win10x64

![2019-07-26_11-38-37](https://user-images.githubusercontent.com/31961530/61938767-899b6e00-af9a-11e9-91d0-aec9ba3d832d.gif)

**Comment by virgilt** [comment]
Hi @AlexandraMoga, may I work on this issue please?

**Comment by caitmuenster** [comment]
Thanks for your interest @virgilt! This is expected behavior and we're going to close as a wontfix. :)
