### ISSUE TITLE
Items in a list should have the same format

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#239]
### Describe the problem and steps to reproduce it:
1. Open https://extensionworkshop-dev.allizom.org/documentation/develop/extensions-and-the-add-on-id/#when-do-you-need-an-add-on-id
2. Observe the `Native-messaging` item

### What happened?
The `Native-messaging` item doesn't have the same format as the rest of the items from the list
### What did you expect to happen?
All list items should have the same format

### Anything else we should know?
- the rest of the list items also have a tooltip with information text at hover, while `Native-messaging` doesn't have that

![image](https://user-images.githubusercontent.com/31961530/61940534-50fd9380-af9e-11e9-9772-f03985d6c2da.png)

**Comment by muffinresearch** [comment]
This is expected, the difference in the format is related to code being marked with backticks and non-code not having that formatting.
