### ISSUE TITLE
Scrolling in the left side panel causes content to scroll in the main page

### ISSUE THREAD

**Issue by acornestean** [mozilla/extension-workshop#243]
### Describe the problem and steps to reproduce it:
Scrolling in the left side panel of any of the “Documentation Topics” sections, “Extensions Basics” and “Community” tabs will cause the main page content to also scroll when reaching the ends in the side panel. Attempting to scroll the content in the main page will not scroll the side panel.

Steps to reproduce:
1. Load the EW page
2. Click on any of the “Documentation Topics” sections, “Extensions Basics” or “Community” tabs
3. Place the cursor on the left side panel
4. Start scrolling down until reaching the end and afterwards continue scrolling (this is also available for when scrolling from the bottom, upwards)
5. Notice that the content of the main page will also scroll

### What happened?
Scrolling in the left side panel causes the main page content to also scroll.

### What did you expect to happen?
Scrolling in the left side panel should not scroll content in the main page.

### Anything else we should know?
The issue was reproduced on FX68 under macOS 10.13.6 and Windows 10 Pro 64-bit.

![Left side panel scrolling](https://user-images.githubusercontent.com/50236075/61948534-bbb7ca80-afb0-11e9-9982-843d68032db8.gif)

**Comment by caitmuenster** [comment]
This is intended behavior. :)
