### ISSUE TITLE
Search result doesn't wrap long unbroken string of characters

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/extension-workshop#250]
### Describe the problem and steps to reproduce it:

1. Open the Extension Workshop website: https://extensionworkshop-dev.allizom.org/.
2. In either of the search fields on the homepage, write a long unbroken string of characters and press Enter.
3. Observe the search results.

### What happened?
The search result page doesn’t wrap the long unbroken string and the page is stretched to git the text. 

### What did you expect to happen?
The search result text should have a wrapped format. 

### Anything else we should know?
Reproduced with Fx68, Win 10x64 and on Android 8.0.0. 

![Long unborken string search](https://user-images.githubusercontent.com/53306802/61955518-e19a9a80-afc3-11e9-996a-1f421d3310cc.gif)

**Comment by caitmuenster** [comment]
@lancecummings, if there's enough time could you look into this?

**Comment by mirunacurtean** [comment]
Confirmed fix on Windows 10 64-bit, Android 8.0.0 and also on MacOS High Sierra 10.13.6 on Dev environment. 
Typing or copying a long unbroken string into any of the search bars in order to perform a search, will show a wrapped search result. 
![long unbroken string wrapped](https://user-images.githubusercontent.com/53306802/63493800-0dc31180-c4c5-11e9-9556-1326526a13d8.gif)
