### ISSUE TITLE
Page header Search field is not dismissed after pressing ESC key

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/extension-workshop#251]
### Describe the problem and steps to reproduce it:

1. Open the Extension Workshop website: https://extensionworkshop-dev.allizom.org/.
2. Click the “Search” key from the right side of the page and the search bar will show. 
3. Press the ESC key.

### What happened?
The search field is not dismissed. 

### What did you expect to happen?
The search field is not dismissed. 

### Anything else we should know?
Reproduced with Fx68, Win 10x64.
Only after clicking “x” the search field is dismissed. 
Reproduced also if clicking outside the search field.

**Comment by caitmuenster** [comment]
@mirunacurtean, do you know if this is an accessibility issue? If it is I am going to make this a high priority.

**Comment by mirunacurtean** [comment]
@caitmuenster Hello. Indeed, I'd include this an an accessibility issue, as it is one of it's requirements, for website functionality to be available from a keyboard.

**Comment by mirunacurtean** [comment]
Confirmed fix on both WIn-64 bit also on Ubuntu 18.04.2 LTS 64-bit. 
Managed to close the page header search bar using the **ESC** key when empty or when text has been inserted. 
![search bar closed using ESC key](https://user-images.githubusercontent.com/53306802/62114557-903e2400-b2bf-11e9-934e-70365635f98e.gif)
