### ISSUE TITLE
No message is received when performing a search using special characters

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/extension-workshop#254]
### Describe the problem and steps to reproduce it:

1. Open the Extension Workshop website: https://extensionworkshop-dev.allizom.org/.
2. Click on either of the search fields available and type in special characters ^*%(*&)*)
3. Observe the result.

### What happened?
Search is performed but no message indicating that there are no search results is displayed. 

### What did you expect to happen?
A message indicating that "No search results have been found for ^*%(*&)*)" or similar should be received.

### Anything else we should know?
![Special character search](https://user-images.githubusercontent.com/53306802/61957819-c8e0b380-afc8-11e9-8bf9-f453a4f90ddf.gif)

**Comment by caitmuenster** [comment]
This would be a nice-to-have; marking it as a p4.

**Comment by mirunacurtean** [comment]
Confirmed fix on Windows 10 64-bit, Android 8.0.0 and also on MacOS High Sierra 10.13.6 on Dev environment.
A "0 search results for [string]" message is displayed, as expected. 
![Special character search](https://user-images.githubusercontent.com/53306802/63494632-ca69a280-c4c6-11e9-8016-cc2f584f58aa.gif)
