### ISSUE TITLE
Unable to find results using some of the documentation topic titles

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/extension-workshop#266]
### Describe the problem and steps to reproduce it:

1. Open the Extension Workshop website: https://extensionworkshop-dev.allizom.org/.
2. In either of the homepage search bars enter one of the following documentation topics titles : "Manage", "Enterprise", "Themes".  
3. View the search results. 

### What happened?
0 search results are found using the specified documentation topic titles. 
Also trying to perform a search for "community" will have the same result. 

### What did you expect to happen?
Search results should be found for The documentations topics and also for other homepage titles like "Extensions basics" and "Community". 

### Anything else we should know?
Reproduced with Fx68, Win 10x64, Ubuntu 18.04.2 LTS 64-bit and Android 8.0.0. 
**Note: Results for the documentation topics titles can be found using a sub-string search, for example: "manag",  "enterpris" or "theme",  making this is to likely be a regression case from https://github.com/mozilla/extension-workshop/issues/249.** 

![Search results are found only using substring](https://user-images.githubusercontent.com/53306802/62115468-2aeb3280-b2c1-11e9-9ae0-c3cbf12d6e5b.gif)

**Comment by muffinresearch** [comment]
Fixed via #292

**Comment by mirunacurtean** [comment]
Confirmed fix on Windows 10 64-bit, Android 8.0.0 and also on Ubuntu 18.04.2 LTS 64-bit on Dev environment.
Search results are listed for any of the documentation topics and also using the "extensions" and the "community" keywords.
