### ISSUE TITLE
Documentation Topics dropdown menu is not closed when user navigates away from the homepage

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#267]
### Describe the problem and steps to reproduce it:

1. Open the extension workshop homepage - https://extensionworkshop-dev.allizom.org/
2. Hover over Documentation Topics and choose any item from the menu to access another page
3. Navigate back to the homepage

### What happened?
The Documentation menu is still open

### What did you expect to happen?
The Documentation menu closes when the user navigates away from the page where the menu was first expanded

### Anything else we should know?
- the menu doesn't close when you scroll up or down
- only by clicking somewhere else in the page, the menu will eventually be closed
- reproduced with Fx68, Win10x64 and Android 8.0

![2019-07-30_16-06-37](https://user-images.githubusercontent.com/31961530/62132218-4d8f4280-b2e5-11e9-879c-8e1b63c90c78.gif)

**Comment by virgilt** [comment]
Hi @AlexandraMoga can I work on this issue?

**Comment by caitmuenster** [comment]
Hi @virgilt! We're currently only accepting patches tagged `contrib: good-first-bug` or `contrib: welcome` for this project. 

We have a [few of those bugs available](https://addons-pm.herokuapp.com/contrib/good-first-bugs/?dir=desc&sort=updatedAt) for other add-ons projects -- would you be interested in checking those out?

**Comment by virgilt** [comment]
@catmuenster I’ll check those out for sure!

**Comment by ritikasource** [comment]
Hi @AlexandraMoga can I claim this issue?

**Comment by digitigrafo** [comment]
I proposed a partial fix for the issue, to close the menu when the user scrolls the page.
About the drop-down menu that stays open when you go in another page and go back: i see that also the dropdown menu of bootstrap libray do the same. You can test here:
https://getbootstrap.com/docs/4.0/components/dropdowns/
So, sounds a bit more hard to change the behavior. Cheers

**Comment by rebloor** [comment]
Tested and no longer an issue.
