### ISSUE TITLE
"Learn fundamentals on MDN" link goes to wrong URL 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#268]
The link on the homepage for "Learn fundamentals on MDN" currently goes to https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/manifest.json. 

It should go to https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/What_are_WebExtensions.

**Comment by Patil2099** [comment]
Can I work on this ?

**Comment by caitmuenster** [comment]
Sure thing @Patil2099!
