### ISSUE TITLE
"Connect with other extension developers" link is wrong 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#269]
On the homepage, the link in the "Connect with other extension developers" goes to https://wiki.mozilla.org/WebExtensions/policy. 

It should go to https://mail.mozilla.org/listinfo/dev-addons.

**Comment by rbrishabh** [comment]
Hey @caitmuenster ! I would love to take this up! :)

**Comment by caitmuenster** [comment]
Go for it @rbrishabh!
