### ISSUE TITLE
Update links on landing page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#284]
In the section "Ready to build an extension for Firefox" on the landing page, links to the documentation topics need to be changed. 

![Screen Shot 2019-08-08 at 9 19 57 AM](https://user-images.githubusercontent.com/23342476/62719891-c9604d80-b9bd-11e9-84b3-b5804387957c.png)

Learn --> link to Extension Basics (/extension-basics/) 
Develop --> link to Develop Overview (/documentation/develop/)
Test & Debug --> link to /documentation/develop/temporary-installation-in-firefox/
Publish --> link to Publish Overview (/documentation/publish/)
Manage --> link to Manage Overview (/documentation/manage/

**Comment by championshuttler** [comment]
cc @megha-kumarii, Here you go!
