### ISSUE TITLE
Local builds are really slow 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#300]
From @muffinresearch at https://github.com/mozilla/extension-workshop/pull/297#issuecomment-522676472: 

> The local builds are only slow when starting from scratch. After you've done it once thereafter a cache is used which speeds it up.

 > However, I suspect that some of the includes are being used heavily across the entire site and the build is probably executing that code over and over again. To fix that we should investigate profiling the build and see if anything sticks out as being particularly slow or accessed a lot of times.

**Comment by muffinresearch** [comment]
I'll run a profile and see what happens.

**Comment by muffinresearch** [comment]
Running profiling locally, a code cache (after running `yarn clean`) it all seems to complete in under 45 secs. 

So I don't think there's a problem, either that or a problem that was there has gone away.

Profile looks like this:

```
Filename                             | Count |   Bytes |   Time
-------------------------------------+-------+---------+-------
_layouts/home.html                   |     1 |  42.90K | 23.384
_layouts/404.html                    |     1 |  84.29K | 19.503
_includes/head.html                  |     4 |   9.44K | 16.931
_includes/home/build.md              |     1 |   6.20K |  9.327
_includes/home/about.md              |     1 |  31.16K |  8.711
_includes/home/connect.md            |     1 |   1.64K |  1.697
_layouts/search-results.html         |     1 |   1.09K |  0.689
_layouts/full-width.html             |     3 | 297.14K |  0.198
_includes/header.html                |     4 | 300.22K |  0.120
_includes/nav.html                   |     4 | 294.98K |  0.115
_layouts/tag-search-results.html     |     1 |   0.50K |  0.002
_includes/footer.html                |     4 |  12.73K |  0.001
_includes/google-analytics.html      |     4 |   2.29K |  0.001
variable)                            |     3 |   0.04K |  0.001
_includes/search-bar.html            |     6 |   1.61K |  0.000
_includes/home/anatomy-v2.svg        |     1 |  13.07K |  0.000
_includes/connect.html               |     4 |  11.27K |  0.000
asset:var:c0df40)                    |     4 |   0.04K |  0.000
asset:var:414477)                    |     4 |   0.04K |  0.000
asset:var:8a92b1)                    |     4 |   0.04K |  0.000
asset:var:ee3d9e)                    |     4 |   0.06K |  0.000
_includes/home/anatomy-v2-mobile.svg |     1 |  11.92K |  0.000
asset:var:3ff1f0)                    |     1 |   0.03K |  0.000
asset:var:05f525)                    |     3 |   0.04K |  0.000
asset:var:830078)                    |     2 |   0.04K |  0.000
asset:var:e3b0c4)                    |     5 |   0.00K |  0.000
asset:var:53a51a)                    |     4 |   0.04K |  0.000
asset:var:b4a84b)                    |     1 |   0.02K |  0.000
asset:var:c0bb45)                    |     1 |   0.02K |  0.000
asset:var:047d19)                    |     1 |   0.01K |  0.000
asset:var:6308d8)                    |     1 |   0.03K |  0.000
asset:var:eca717)                    |     2 |   0.03K |  0.000
asset:var:ea53d9)                    |     1 |   0.02K |  0.000
asset:var:def8af)                    |     2 |   0.05K |  0.000
asset:var:2da4bc)                    |     1 |   0.02K |  0.000
asset:var:71749c)                    |     1 |   0.03K |  0.000
asset:var:5c0ad7)                    |     1 |   0.03K |  0.000
asset:var:cf15fd)                    |     1 |   0.02K |  0.000
asset:var:610cb5)                    |     1 |   0.03K |  0.000
asset:var:e09dfb)                    |     1 |   0.01K |  0.000
asset:var:6399cf)                    |     1 |   0.02K |  0.000
asset:var:3053d6)                    |     1 |   0.04K |  0.000
asset:var:b0cb9d)                    |     1 |   0.03K |  0.000
asset:var:79a852)                    |     1 |   0.03K |  0.000
asset:var:4a0e44)                    |     1 |   0.03K |  0.000
asset:var:b95fc8)                    |     1 |   0.02K |  0.000
asset:var:8850c5)                    |     1 |   0.03K |  0.000
asset:var:07436a)                    |     1 |   0.02K |  0.000
asset:var:adb09b)                    |     1 |   0.02K |  0.000
asset:var:3a888d)                    |     1 |   0.02K |  0.000
```

You can run it yourself with:

`yarn clean && JEKYLL_ENV=production SVGO_BIN='node_modules/svgo/bin/svgo' jekyll build --profile`

I'd also be interested in what other people are seeing for:

`yarn clean && yarn build` 

It outputs the time taken itself so running that without `time` in front of it is fine.

**Comment by muffinresearch** [comment]
Looking at this there's a lot of these includes that rely on page context, so fixing this would require a fair bit of refactoring.

A quick test with include caching ignoring the potential breakage didn't show much of an improvement. Still showing north of 420s.

Going back to running master and focusing on the local dev issue:

* A cold cache `yarn clean && yarn start` takes:  457.706 seconds
* A follow-up `yarn start` takes: 20.57 seconds
* Enabling the experimental incremental build option 1st run: 21.087 seconds
* 2nd run with incremental builds enabled:  0.182 seconds 🎉

But be warned incremental builds are experimental - so if we enable this we'll need to see how it  goes. See https://jekyllrb.com/docs/configuration/incremental-regeneration/ for details.

I'll put a PR up for that shortly.
