### ISSUE TITLE
Update links on Develop Overview Page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#309]
Now that we have more pages built out, it's time to update links on the Develop Overview page! 

### Firefox Tools
- [x] "a version of Firefox" should link to `/documentation/develop/choosing-a-firefox-version-for-extension-development/`
- [x] "extension development tools" should link to `/documentation/develop/browser-extension-development-tools/`

### User Experience
- [x] "onboarding flow" should link to `/documentation/develop/onboard-upboard-offboard-users/`
- [x] "best practices for collecting user data consent" should link to `/documentation/develop/best-practices-for-collecting-user-data-consents/`
- [x] "request the right permissions" should link to `/documentation/develop/request-the-right-permissions/`
- [x] "user experience best practices" should link to `/documentation/develop/user-experience-best-practices/`
- [x] "build an accessible extension" should link to `/documentation/develop/build-an-accessible-extension/`
- [x] "building a secure extension" should link to `/documentation/develop/build-a-secure-extension/`

### Firefox for Android

- [x] "differences between Firefox for the desktop and Android" should link to `/documentation/develop/differences-between-desktop-and-android-extensions/`
- [x] "developing for Firefox for Android" should link to `/documentation/develop/developing-extensions-for-firefox-for-android/`

### Port to Firefox 

- [ ] " porting guide" should link to `/documentation/develop/porting-a-google-chrome-extension/`
- [x] "legacy Firefox extension" should link to `/documentation/develop/porting-a-legacy-firefox-extension/`
- [x] "Add-on SDK" should link to `/documentation/develop/comparison-with-the-add-on-sdk/`
- [x] "XUL/XPCOM" should link to `/documentation/develop/comparison-with-xul-xpcom-extensions/`

### Test and debug
- [x] "debug your code" should link to `/documentation/develop/debugging/`
- [x] "temporarily installing" should link to `/documentation/develop/temporary-installation-in-firefox/`
- [x] " test persistent and restart features" should link to `/documentation/develop/testing-persistent-and-restart-features/`
- [x] "permission requests" should link to `documentation/develop/test-permission-requests/`
- [x] "web-ext" should link to `/documentation/develop/getting-started-with-web-ext/`

**Comment by championshuttler** [comment]
cc @megha-kumarii

**Comment by megha-kumarii** [comment]
Working on it:)

**Comment by caitmuenster** [comment]
Woohoo, thank you so much, @apsychogirl! ✨

One last request -- could you update the "porting guide" link to " `/documentation/develop/developing-extensions-for-firefox-for-android/`? Then we can fully close this issue out. 💪🏼

**Comment by championshuttler** [comment]
@caitmuenster https://github.com/mozilla/extension-workshop/blob/f7816bdec6ecddece3858ef8abd10c95f7496f9f/documentation/develop.md#L239,

I think its done already if i am not wrong

**Comment by caitmuenster** [comment]
Check out line 239 -- it currently links to Developing Extensions for Android. :)

**Comment by championshuttler** [comment]
Oops, got it, current link is `/documentation/develop/porting-a-google-chrome-extension/` we mentioned wrong link in issue description then ;)

**Comment by caitmuenster** [comment]
Ahhh sorry! That was totally my fault!
