### ISSUE TITLE
Update links on the landing page

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#313]
The following links need to be updated on the landing page: 

- [ ] "Learn about security best practices" should link to `/documentation/develop/build-a-secure-extension/`
- [ ] "learn about our policies" should link to `/documentation/publish/add-on-policies/`

**Comment by mahimas28** [comment]
hey can i work on this bug?

**Comment by championshuttler** [comment]
@mahimas28 Certainly yes. Feel free to raise the PR :)
