### ISSUE TITLE
Update sidebar links 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#322]
The following links need to be updated in the Develop section of the sidebar: 

- [x] **Web-ext Webpack plug-in** needs to link to `https://github.com/hiikezoe/web-ext-webpack-plugin/blob/master/README.md`
- [x] **Browser API Polyfill** needs to link to `https://github.com/mozilla/webextension-polyfill`
- [x] **What’s great content and design?** needs to link to `https://www.youtube.com/watch?v=a0_OsLGI0k4`
- [x] **Extension compatibility test** needs to link to `https://www.extensiontest.com/`

**Comment by ruchikabgosain** [comment]
@caitmuenster squashing this one too! Haha :D

**Comment by caitmuenster** [comment]
@ruchikabgosain  Awesome! 💪🏼

You need to go to the `data` folder and edit the `pages.yaml` file. Let me know if you need any help. :)
