### ISSUE TITLE
Build page for "Updating Your Extension" 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#331]
We need to port the content of the [MDN page for Updates](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Updates) to Extension Workshop. 

- [x] Create new page in the "Manage" folder. The page should be titled "Updating your extension." 
- [x] Update sidebar (make sure to include subpage items!) in the `pages.yaml` file. "Updating your extension" should be the first item in the sidebar list under Overview. 

See the `sidebar-master-template` file for styling code. 

@championshuttler, do you want to take this one?

**Comment by ruchikabgosain** [comment]
Hello @caitmuenster, as per our conversation, what changes do I need to make for the sidebar? 

Cc: @championshuttler

**Comment by caitmuenster** [comment]
Hey @ruchikabgosain! 

You will need to edit the `pages.yaml` file in the `_data` folder. Scroll to the "Manage" section and look for the category called "Resources."

You will need to add "Updating your extension" as a new page and also add the subpage items based on the h2 (##) headings. 

Let me know if you need any help!

**Comment by ruchikabgosain** [comment]
Just a lil question: `documentation/manage/updating-your-extension.md` : this is the file i need to refer for the H2, right?

**Comment by caitmuenster** [comment]
@ruchikabgosain Yes! Thanks for checking :)

**Comment by caitmuenster** [comment]
Closed by #332 and #342.
