### ISSUE TITLE
Update the .gitignore file

### ISSUE THREAD

**Issue by championshuttler** [mozilla/extension-workshop#334]
We should increase the list in .gitignore to ignore the files like `.DS_Store`. For example added in #304 by mistake.

**Comment by ruchikabgosain** [comment]
I would like to work on this one. Is this open? @championshuttler

**Comment by caitmuenster** [comment]
@ruchikabgosain It looks like @championshuttler already has a PR up (#335). Would you be interested in finishing off #331 instead? We just need to add that page to the sidebar. :)

**Comment by ruchikabgosain** [comment]
Ah yes, my bad. Yes, i would love to finish #335. Thank you @caitmuenster ✨😁
