### ISSUE TITLE
Update links on Firefox workflow overview

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#350]
- [x] Code your extension (currently results in 404) 
- [x] Promote your extension
- [x] Featured extensions
- [x] Update your extension
- [x] Sideloading add-ons (currently results in 404)
- [x] Desktop apps (currently results in 404)
- [x] Enterprise (currently results in 404)

**Comment by ruchikabgosain** [comment]
Hey @caitmuenster, can I take this up?
AFAIK, this links from #245

**Comment by caitmuenster** [comment]
@ruchikabgosain This one's all yours! 

All of these links need to go to the correct pages hosted on EW, except for Code Your Extension. Let's actually remove the link to Code Your Extension for now (I'm not seeing any good docs to link it to at the moment).

**Comment by ruchikabgosain** [comment]
Taking this up right away! Just a lil confirmation: the edits go in `pages.yaml` right?

**Comment by caitmuenster** [comment]
Thanks for checking! These edits are going to go directly on the `firefox-workflow-overview.md` file. :)
