### ISSUE TITLE
Update links on Browser Extension Development Tools 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#351]
- [x] web-ext get started
- [x] web-ext command reference
- [x] Developing extensions for Firefox for Android

**Comment by championshuttler** [comment]
If I am not wrong, these should be linked to :
1. `/documentation/develop/getting-started-with-web-ext/`
2. `/documentation/develop/web-ext-command-reference/`
3. `/documentation/develop/developing-extensions-for-firefox-for-android/`

**Comment by caitmuenster** [comment]
Thanks for filling in those gaps @championshuttler! Opening this bug up for contributors. :)

**Comment by championshuttler** [comment]
cc @dcipher00

**Comment by ruchikabgosain** [comment]
Hey @dcipher00 will you be taking this up? If not, let me know, I would like go ahead with this :)
