### ISSUE TITLE
Update links on Browser compatibility page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#352]
- [ ]  Building a cross-browser extension

**Comment by ruchikabgosain** [comment]
Fixing this one @caitmuenster 🍔

**Comment by ruchikabgosain** [comment]
Checked this one! The link seems to be working. What change do we need to make exactly?

**Comment by caitmuenster** [comment]
@ruchikabgosain My bad - this issue is invald. Nothing to do on the browser compatibility page!

**Comment by ruchikabgosain** [comment]
Okay! @caitmuenster 🌟
