### ISSUE TITLE
Update links on Choosing a Firefox version for extension development 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#353]
- [ ] all instances of web-ext should link to EW page on "getting started with web-ext"
- [x] all locales should be removed from links

**Comment by championshuttler** [comment]
@alankritgupta091099 interested in working on it? let me know if you need any help.

**Comment by championshuttler** [comment]
So , here is the starting point http://localhost:4000/documentation/develop/choosing-a-firefox-version-for-extension-development/ on this page , you have to link every instance of `web-ext` to `/documentation/develop/getting-started-with-web-ext/` and remove `en-US` from the mdn links if its getting used, for example here https://github.com/mozilla/extension-workshop/blob/fc7e0ee518ab464192b2c945d70e279d039ea6d6/documentation/develop/getting-started-with-web-ext.md#L186 The link should be changed to `https://developer.mozilla.org/docs/Tools/Remote_Debugging/Firefox_for_Android#Connecting`

**Comment by ruchikabgosain** [comment]
Hey @alankritgupta091099 would you be interested in working on this? Let me know, if not, id be happy to take this up :)

**Comment by virgilt** [comment]
@championshuttler can I work on this? This is my first contribution to Mozilla. I want to be a consistent contributor for HTML, CSS, and JavaScript projects.

**Comment by championshuttler** [comment]
@virgilt Yeah absolutely , Go for it. Thank you!. Let me know if you need any help :)

**Comment by championshuttler** [comment]
Hey @virgilt , do you need any help. If you are getting stuck, please feel free to ask!

**Comment by virgilt** [comment]
@championshuttler I was setting up the build on Linux, never done anything like this before. I'll be working on the issue now.

**Comment by virgilt** [comment]
@championshuttler Not sure if I am missing something here. All references of `web-ext` on [http://localhost:4000/documentation/develop/choosing-a-firefox-version-for-extension-development/](url) are already pointing to `/documentation/develop/getting-started-with-web-ext/`

**Comment by caitmuenster** [comment]
Sorry about that @virgilt -- indeed, all references of web-ext were pointing to the right place in that doc.
