### ISSUE TITLE
Update links on Getting started with web-ext page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#354]
- [ ]  limitations regarding prompts for permissions and restart features --> `/documentation/develop/testing-persistent-and-restart-features/`
- [ ] run reference guide --> create anchor link for and link to `documentation/develop/web-ext-command-reference/` run section
set up your computer and device --> link to `/documentation/develop/developing-extensions-for-firefox-for-android/`
- [ ] too many other links to list :(

**Comment by ruchikabgosain** [comment]
Hey @caitmuenster can I take this up?

**Comment by caitmuenster** [comment]
@ruchikabgosain I'm almost done with this but I will throw you the next one that needs work!

**Comment by ruchikabgosain** [comment]
Ah, sounds good! 🚀

**Comment by caitmuenster** [comment]
Closed by #358 .
