### ISSUE TITLE
Update links on Security Best Practices page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#359]
A number of links need to be updated on `build-a-secure-extension.md`: 

- [ ] document.createElement, Element.setAtttribute, Node.textContent --> MDN pages 
- [ ] Safely inserting external content into a page. --> ?? 
- [ ]  eval(), content_security_policy --> MDN
- [ ] Default content security policy --> MDN 
- [ ] built-in extension UI features --> https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/user_interface
- [ ] data URLs  --> MDN
- [ ] data URL --> MDN
- [ ] srcdoc --> MDN

**Tip:** If you replace `https://extensionworkshop-dev.allizom.org/` with `https://https://developer.mozilla.org/`, you might land on the MDN page for that topic. If you do, use that link (without the localization code).

**Comment by caitmuenster** [comment]
@ruchikabgosain Want to give this one a go? It requires a bit of double checking your work but I think you've got this. :)

**Comment by ruchikabgosain** [comment]
@caitmuenster thankyou for this! it's on me! 😄
