### ISSUE TITLE
Update links for Requesting the Right Permissions 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#360]
The following links need to be updated in the `request-the-right-permissions.md` file: 

- [ ] when you load an unpacked extension --> `/documentation/develop/temporary-installation-in-firefox/`
- [ ] Test permission requests --> `/documentation/develop/test-permission-requests/`

**Comment by ruchikabgosain** [comment]
Fixing this one! @caitmuenster 🍏
