### ISSUE TITLE
Update links: Best practices for collecting user data consents 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#361]
The following links need to be updated in the `best-practices-for-collecting-user-data-consents.md` file: 

- [x] Data Disclosure, Collection and Management  --> `/documentation/publish/add-on-policies/#data-disclosure-collection-and-management`
- [x] Add-on Policies --> `/documentation/publish/add-on-policies/`
- [x] Best practices for onboarding, upboarding, and offboarding users. --> `/documentation/develop/onboard-upboard-offboard-users/`

**Note:** Several of these links appear multiple times; please update all links in the file. 

Related issue #245.

**Comment by ruchikabgosain** [comment]
Can I fix this? @caitmuenster 😀

**Comment by caitmuenster** [comment]
Go for it @ruchikabgosain!
