### ISSUE TITLE
Update links on Build an Accessible Extension Page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#362]
Related to #245. 

All of the links that are 404'ing in the `build-an-accessible-extension.md` file need updating. 

There is a good chance that replacing the prefix`https://https://extensionworkshop-dev.allizom.org` with `https://developer.mozilla.org` will lead you to the MDN page for that topic. We need these links to point to those MDN pages, without the localization coding.

**Comment by ruchikabgosain** [comment]
Fixing this one! @caitmuenster 🍒
