### ISSUE TITLE
Update links on User Experience Best Practices page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#363]
Related to #245.

The following links need to be updated on `user-experience-best-practices.md`: 

- [x]  Add-on Policies --> `/documentation/publish/add-on-policies/`
- [x] Best practices for onboarding, upboarding, and offboarding users --> `/documentation/develop/onboard-upboard-offboard-users/`
- [x] identify your extension as “experimental” --> `/documentation/publish/submitting-an-add-on/#listing-on-amo`
- [x] beta or other non-final release --> `/documentation/publish/signing-and-distribution-overview/`
 - [x] Sideloading add-ons --> `/documentation/publish/distribute-sideloading/`

**Comment by ruchikabgosain** [comment]
Hey @caitmuenster can I work on this?
