### ISSUE TITLE
Fix links on Publish overview page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#373]
The following links need to be updated in the `publish.md` file: 

- [ ] "mechanisms designed to enable enterprise browser administrators to install add-ons "should link to `/documentation/enterprise/enterprise-distribution/`
- [ ] "some things you should consider" should link to `/documentation/publish/self-distribution/`

**Comment by apsychogirl** [comment]
Can I fix this up?

**Comment by caitmuenster** [comment]
@apsychogirl Yes, go for it!
