### ISSUE TITLE
Fix links on Add-on Policies page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#374]
The following links need to be updated in the `add-on-policies.md` file: 

- [ ] "uploaded for self-distribution" should link to `/documentation/publish/submitting-an-add-on/#self-distribution`
- [ ] "third party library guidelines" should link to `/documentation/publish/third-party-library-usage/`
- [ ] "What does review rejection mean to users?" should link to `/documentation/publish/what-does-review-rejection-mean-to-users/`

**Comment by apsychogirl** [comment]
Can I fix this up?

**Comment by ruchikabgosain** [comment]
Fixed this one! 🍎
