### ISSUE TITLE
Update links on Source Code Submission page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#376]
The following links need to be updated in the `source-code-submission.md` file: 

- [ ] "our requirements" should link to `/documentation/publish/third-party-library-usage/`

**Comment by apsychogirl** [comment]
Can I work on this?

**Comment by caitmuenster** [comment]
@apsychogirl Let's leave this one open for others while you are working on the other issues. :) If this is still open when those PRs come in, this one is yours.

**Comment by caitmuenster** [comment]
Hmm -- this is currently 404'ing on dev. Reopening and tagging myself (@caitmuenster) for investigation.

**Comment by caitmuenster** [comment]
Yay this is up now!
