### ISSUE TITLE
Update link & sidebar order on Manage overview page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#378]
The following links should be updated in the `manage.md` file: 

- [x] "add-ons on AMO can have multiple authors." should link to `/documentation/publish/add-on-ownership/`

The sidebar (`_data.yaml` file)should be re-ordered to: 

- Updating your extension
- Best practices for updating your extension
- Resources for publishers
- Retiring your extension

**Comment by apsychogirl** [comment]
Can I take this up?

**Comment by championshuttler** [comment]
Yes @apsychogirl go for it!. Thank you :)
