### ISSUE TITLE
Fix typos, links on Enterprise overview page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#379]
### Copy fixes 

- [x]   "Some Firefox enterprise policies might affect the extension.com"  should read " Some Firefox enterprise policies might affect the installation, behavior, and update of extensions."
- [x] addons.org should be `addons.mozilla.org` and should link to https://addons.mozilla.org 
- [x] "enterprise distribution" should link to `/documentation/enterprise/enterprise-distribution/`
- [x] Add "enterprise" as a tag for the page

**Comment by apsychogirl** [comment]
Hey! Can I work on this?

**Comment by championshuttler** [comment]
Yes @apsychogirl go for it!. Thank you :)
