### ISSUE TITLE
Update links on Enterprise distribution page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#380]
The following links should be updated in the `enterprise-distribution.md` file: 

- [x] "Installation using standard extension folders" should link to `/documentation/publish/distribute-sideloading/#standard-extension-folders`
- [x] "administrative config" should link to `https://support.mozilla.org/products/firefox-enterprise/policies-customization-enterprise/policies-overview-enterprise`

**Comment by apsychogirl** [comment]
Can I take this up?

**Comment by championshuttler** [comment]
Yes @apsychogirl go for it!. Thank you :)

**Comment by caitmuenster** [comment]
Hmm -- flagging this for myself (@caitmuenster) because the changes don't seem to be showing up in https://extensionworkshop-dev.allizom.org/.

**Comment by caitmuenster** [comment]
This is working! Yay!
