### ISSUE TITLE
The search dismiss button `x` is not diplayed on Firefox

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#403]
STR:
1. Load the homepage https://extensionworkshop-dev.allizom.org/
2. Go to the second search bar (not the one at the top of the page)
3. Type in a search query 
4. Try to dismiss it using `x` 

Expected result:
Search is dismissed.

Actual result:
`x` button is not available.

Note:
This issue is reproducible on EW dev (Win10) with FF69.
It is not reproducible with Chrome. 

FF

![weeird](https://user-images.githubusercontent.com/33448286/64954360-0a396500-d88e-11e9-8db9-3522bf79262a.png)

Chrome

![as in Chrome](https://user-images.githubusercontent.com/33448286/64954482-61d7d080-d88e-11e9-9f33-de1f574c546a.png)

**Comment by rbrishabh** [comment]
Hey! I would like to take this up!

**Comment by muffinresearch** [comment]
This isn't a bug it's just a difference in default browser behaviour see: https://jsbin.com/kumixo/1/edit?html,output
