### ISSUE TITLE
Esc Key won't delete the search on FF 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#404]
STR:
1. Load the homepage https://extensionworkshop-dev.allizom.org/
2. Go to the second search bar (not the one at the top of the page)
3. Make a search
4. Try to dismiss it using `ESC` key

Actual result:
Nothing happens. 

Expected result:
The search is dismissed.

Notes:
Reproducible on EW dev - FF69(Win10).
It not reproducible on Chrome.

FF

![using esc on ff](https://user-images.githubusercontent.com/33448286/64955528-22f74a00-d891-11e9-864c-f28978b5df93.gif)

Chrome 

![using esc on chrome](https://user-images.githubusercontent.com/33448286/64955539-2c80b200-d891-11e9-9e33-80118ce2ead7.gif)

**Comment by caitmuenster** [comment]
Thanks @ioanarusiczki, this looks like it's behaving as expected. Since that text box lives permanently on that part of the page, it's ok to that you can't escape it.

**Comment by ioanarusiczki** [comment]
@caitmuenster Sorry I did not write this down correctly.  
It is about deleting the search term used not about dismissing the search bar.
If I use `esc` key on Chrome (as I showed above - the button helps deleting the text). 
I will update it correctly and reopen.

**Comment by muffinresearch** [comment]
This is just a difference in how FF and chrome handle `<input type="search" />`. See https://jsbin.com/kumixo/edit?html,output

As such I don't think this necessarily needs a fix.
