### ISSUE TITLE
Extensions Developer Newsletter - the E-mail address stays highlighted in red on FF, it never shows a red highlight on Chrome

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#407]
I've noticed an inconsistency on how FF behaves compared to Chrome.

On FF:
1. Go to Extensions Developer Newsletter and type in an invalid e-mail address (check the box below)
2. Click Sign up and observe the screen

Result: 
E-mail Adress is highlighted in red and a warning message is displayed.

Notes:
If after the above steps I delete the invalid address the box stays highlighted in red. If I type in a valid address then land on https://www.mozilla.org/en-US/newsletter/ and return to EW page with the Back button the red highlight is still displayed.
If I refresh the page the red highlight is still displayed.
I found a workaround when the red highlight turns back to blue: clicking on the header of the page.

![red highlight](https://user-images.githubusercontent.com/33448286/65162044-4f51c880-da41-11e9-85da-18c0d8991c84.gif)

On Chrome 
If I enter an invalid e-mail address the warning is present but there is no red highlight of the box. 
It stays highlighted in blue in all situations. 

![blue highlight](https://user-images.githubusercontent.com/33448286/65162464-f171b080-da41-11e9-9dd5-2008a00c9fe8.gif)

**Comment by muffinresearch** [comment]
This is a difference in the standard behaviour between chrome and Firefox for HTML5 validation see: https://jsbin.com/hazafof/edit?html,output

As such I don't think a fix is necessary.
