### ISSUE TITLE
[Test-permission-requests] Link pointing to addons.mozilla.org is incorrect

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#414]
### Describe the problem and steps to reproduce it:

1. Open the following documentation page - https://extensionworkshop-dev.allizom.org/documentation/develop/test-permission-requests/#observe-or-verify-install-time-permission-requests
2. Click on  the `addons.mozilla.org` link displayed below:

![image](https://user-images.githubusercontent.com/31961530/65330039-71268900-dbc2-11e9-9eaa-02f04520b6a2.png)

### What happened?
The links is mapped to https://addon.mozilla.org which is invalid ("addon" is missing an 's' at the end)
### What did you expect to happen?
The link should point to https://addons.mozilla.org

**Comment by championshuttler** [comment]
Hi @virgilt , are you interested in working on this one?

**Comment by virgilt** [comment]
@championshuttler Yes, absolutely interested!

**Comment by championshuttler** [comment]
Awesome @virgilt , it would be great if you can raise the PR till monday, no pressure though, we are going to freeze the code next week :)

**Comment by virgilt** [comment]
@championshuttler I am working on it now so I will try to finish it today.

**Comment by AlexandraMoga** [comment]
Link is pointing to the correct website now.
