### ISSUE TITLE
Setup a staging site

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#42]
Since we need to iron out some CSP config issues would it be possible to deploy in the same way that we'd deploy to production on a staging site.

Maybe extensionsworkshop.allizom.org could be used or something else? This should be built from master. This way we can iron out the CSP config issues and any other deployment wrinkles ahead of the site being live on https://extensionsworkshop.com.

**Comment by muffinresearch** [comment]
Once this is setup we can disable the gh-pages builds because they won't work with the assets pipeline anyway.

**Comment by caitmuenster** [comment]
Ok, it looks like the stage environment is set up! 🎉 @bqbn, if you could get the basic site up on stage by EOD Monday, that would be great. @muffinresearch will be back from PTO on Tuesday and can start fine-tuning the CSP when he gets back.

**Comment by bqbn** [comment]
The site is up: https://extensionworkshop.allizom.org/

"master" branch is set up to push to the above site automatically.
