### ISSUE TITLE
A resource linked in the Package your extension page is not available

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#425]
### Describe the problem and steps to reproduce it:
1. Open the following section from the Package your extension page  - https://extensionworkshop-dev.allizom.org/documentation/publish/package-your-extension/#package-linux
2. Click on the following link from the information banner:

![image](https://user-images.githubusercontent.com/31961530/65412045-1b86f200-ddf7-11e9-830a-0d64c50b4f0d.png)

### What happened?
The linked page doesn't exist (a 404 is raised by the linked site)

### What did you expect to happen?
The resource should be opened

### Anything else we should know?
@caitmuenster I'm not sure if we are using a wrong link or if the destination page is indeed not available anymore. In any case, this link should be updated.

**Comment by championshuttler** [comment]
I guess link should be - http://infozip.sourceforge.net/Zip.html

**Comment by muffinresearch** [comment]
Looks like the link is broken on their site too: see http://infozip.sourceforge.net/ and scroll down to "Info-ZIP Downloads".

<img width="994" alt="Info-ZIP_Home_Page" src="https://user-images.githubusercontent.com/1514/65418590-b03c2080-ddf4-11e9-9475-7f1cf1c7f50a.png">

Looking at wayback machine this page is man page documentation, so we could probably use something like https://linux.die.net/man/1/zip as an alternative.

**Comment by AlexandraMoga** [comment]
The links was updated to the one recommended in the comment above.
