### ISSUE TITLE
Layout issues in search results when searching from a tag

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#428]
### Describe the problem and steps to reproduce it:
1. Open any documentation page - i.e https://extensionworkshop-dev.allizom.org/documentation/manage/updating-your-extension/
2. Scroll down to the bottom of the page and click on any of the listed tags - i.e `distribution`
![image](https://user-images.githubusercontent.com/31961530/65417596-116af080-de03-11e9-92c9-c24b51769afe.png)

3. Check the layout of the search results list

### What happened?
Search results are numbered, but the number is not displayed on the same line as the actual search result  

![image](https://user-images.githubusercontent.com/31961530/65417652-35c6cd00-de03-11e9-98e8-f415c45745c2.png)

### What did you expect to happen?
Search results and their corresponding numbers should be displayed on the same line

### Anything else we should know?
When searching from the homepage search field, the results are not numbered. We should decide if tag search needs to use the same layout, or if the numbering should be kept.

**Comment by piculet** [comment]
Can i take this up?

**Comment by piculet** [comment]
Is this issue open to work?

**Comment by muffinresearch** [comment]
This was fixed when tags and search layout was unified in https://github.com/mozilla/extension-workshop/commit/df86577d4daf0be20437281b7e32e71101752b9a
