### ISSUE TITLE
[Android] Menu and dropdown become inactive when changing orientation

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#433]
STR:
1. Load https://extensionworkshop-dev.allizom.org/ on a tablet in it's original orientation (landscape).
2. Go to a tab - extension Basics or any other
3. Change orientation into portrait
4. Tap the Menu button or the drop down bar (where the links from the pages are available)

Expected result:
The Menu is displayed. The drop down list is available. 

Actual result:
Both buttons are inactive.

Notes:
This issue is reproducible on tablets. I tested with a Samsung and a Huawei tablet both with Android 8.0. 
It is reproducible on all pages (including Homepage). 
I could not reproduce it with small devices - phones. 

![Menu is inactive](https://user-images.githubusercontent.com/33448286/65426888-d1fbce80-de19-11e9-9878-156f92c9b824.gif)

As a workaround: if the page is refreshed the buttons will work again.

**Comment by caitmuenster** [comment]
@muffinresearch What do you think about this?

**Comment by muffinresearch** [comment]
Definitely should be fixed.

**Comment by ioanarusiczki** [comment]
@muffinresearch Verified on FF69 (Android 8.0.0) with Huawei Media Pad.

![the tablet fix](https://user-images.githubusercontent.com/33448286/65672313-7c116b80-e051-11e9-9021-88382ee8d549.gif)

It's also visible in the .gif above -  when I'm going into a subsection (Develop, Publish etc) from Documentation Topics and switch orientation I will only have the drop down menu displayed and I need to scroll up to see the hamburger menu with the search bar.  It is not reproducible the second time (repeating the action). 
If an issue is needed please let me know.
