### ISSUE TITLE
[Mobile] Firefox workflow overview page has layout issues on smaller screen sizes 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#434]
### Describe the problem and steps to reproduce it:
1. Open the Firefox workflow overview documentation page on a mobile device - https://extensionworkshop-dev.allizom.org/documentation/develop/firefox-workflow-overview/
2. Observe the table layout

### What happened?
The table is hard to read

### What did you expect to happen?
The table should be easier to read on smaller screen sizes

### Anything else we should know?
 [layout in portrait orientation]
![image](https://user-images.githubusercontent.com/31961530/65430080-f35fb900-de1f-11e9-919f-ca157e49e968.png)

 [layout in landscape orientation]
![image](https://user-images.githubusercontent.com/31961530/65430099-fbb7f400-de1f-11e9-835f-e63fbb748e1a.png)

**Note**
- Notice also how the images used in the table headers have irregular sizes

**Comment by muffinresearch** [comment]
This was fixed with removal of the images.

**Comment by AlexandraMoga** [comment]
The removal of images from the table header has improved readability, but I think that the header titles are too big. 

![image](https://user-images.githubusercontent.com/31961530/65667145-c4c42700-e047-11e9-8d1b-3890b93ea720.png)


Maybe we can reduce the font size a bit?
I filed a follow up for his - see #464
