### ISSUE TITLE
[MacOS] Tab key navigation does not work as expected

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#435]
STR:
1. Load https://extensionworkshop-dev.allizom.org/
2. Using the mouse, click anywhere before a link on the page and then using `Tab` key try to navigate to the next link or element on the page
3. Observe the page

Expected result:
The next link or element is highlighted and using `enter` key it can be accessed. 

Actual result:
It will jump at the bottom of the page to Newsletter.

Notes:
It is reproducible on MacOS - Mojave 10.14.6 with FF69.
It is reproducible on all pages on EW. 
Not reproducible with Chrome. 

![1](https://user-images.githubusercontent.com/33448286/65433358-86e7b880-de25-11e9-8769-6bef935cb977.gif)

**Comment by caitmuenster** [comment]
@muffinresearch to investigate. We don't think this is a blocker to release.

**Comment by muffinresearch** [comment]
> Using `Tab` key click anywhere before a link on the page and then using `Tab` key try to navigate to the next link or element on the page

I'm not sure I follow this part of the STR. Should the first part "Using `Tab` key click" refer to using the mouse rather than the tab key?

**Comment by ioanarusiczki** [comment]
@muffinresearch My mistake. I was in a hurry and did not write in down clearly.  I meant using the mouse, yes!

**Comment by muffinresearch** [comment]
I can't repro this following the STR so far.
