### ISSUE TITLE
The 'Up Next' cell title should be centered when there is no section title present in the cell

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#439]
### Describe the problem and steps to reproduce it:
1. Open the following documentation page, which is also the last entry from the 'Manage' section - https://extensionworkshop-dev.allizom.org/documentation/manage/retiring-your-extension/
2. Scroll down to the bottom of the page and check the "Up next" navigation cells

### What happened?
The "Enterprise" cell title is not centered most likely because there is no section title present at this point

### What did you expect to happen?
Cell titles should be centered also when there is no section title present

![image](https://user-images.githubusercontent.com/31961530/65439033-35dcc200-de2f-11e9-9457-e454077c04cf.png)

**Comment by muffinresearch** [comment]
I'm not sure this is something that should be fixed "Enterprise" on the left *is* the heading/title.

**Comment by AlexandraMoga** [comment]
That's also what I've thought initially, but then I noticed that on smaller screen sizes the tile is centered. This is why I was wondering why we can't have the same layout on normal/large screens:

[small screen]
![image](https://user-images.githubusercontent.com/31961530/65490138-43d52600-deb5-11e9-83f2-aa3f4a737a9a.png)

**Comment by muffinresearch** [comment]
I personally find the current layout fine, I think if the heading was central vertically on the desktop layout it would look more like a bug than it does now.

**Comment by caitmuenster** [comment]
I'm ok with it as is. If we get any complaints during soft launch, we can revisit this, but otherwise I don't think this needs fixing.
