### ISSUE TITLE
Paragraphs in the Add-on Distribution agreement  page should have the same layout

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#447]
### Describe the problem and steps to reproduce it:

1. Open the Add-on Distribution agreement documentation page - https://extensionworkshop-dev.allizom.org/documentation/publish/firefox-add-on-distribution-agreement/
2. Check the paragraph titles for the consecutive page sections

### What happened?
- For the [Distribution, certificates, & review process](https://extensionworkshop-dev.allizom.org/documentation/publish/firefox-add-on-distribution-agreement/#distribution-certificates-and-review-process) section, paragraph markers are placed on a different line

![image](https://user-images.githubusercontent.com/31961530/65492022-d925e980-deb8-11e9-99e5-50821370076f.png)

- For the rest of the sections, paragraph markers are not placed on a different line:

![image](https://user-images.githubusercontent.com/31961530/65492156-1d18ee80-deb9-11e9-802b-05d6fa971c56.png)

### What did you expect to happen?
All paragraphs should have the same layout. Personally, I prefer the second example because it makes the whole page look more condensed.

**Comment by caitmuenster** [comment]
The formatting of the line separations is intended and does not need to be fixed (see the [page](https://developer.mozilla.org/docs/Mozilla/Add-ons/AMO/Policy/Agreement) on MDN for reference). 

It does look like  h4 text on EW does not seem that much bigger than paragraph text. I'm ok with this at the moment but we can keep it in mind if there is confusion in the future.
