### ISSUE TITLE
The warnings shown for a search with less than 3 chars or an empty search are still visible after scrolling down 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#450]
Similar to https://github.com/mozilla/extension-workshop/issues/405

1. Load https://extensionworkshop-dev.allizom.org/ and make a blank search and after the warning is displayed start scrolling down. Repeat the step for a search with less than 3 chars.

Expected result:
The message is dismissed.

Actual result:
The message is not automatically dismissed.

Notes:
This is reproducible on EW dev with FF69(Win10 &MacOS Mojave 10.14.6).
It is not reproducible on Android 8.0.
It is reproducible for `Please fill out this field` or `Please please check this box if you want to proceed` from the Newsletter. 

![warnings stay on the screen](https://user-images.githubusercontent.com/33448286/65508306-970ca000-ded8-11e9-9201-4ba6a62cb735.gif)

**Comment by muffinresearch** [comment]
This is using HTML5 implemented in the browser. Sounds like https://bugzilla.mozilla.org/show_bug.cgi?id=643758

**Comment by ioanarusiczki** [comment]
@muffinresearch Yes, it is the same UX problem described in https://bugzilla.mozilla.org/show_bug.cgi?id=643758 which was opened 9 years ago. 
I see it as a minor UX issue, but who knows, maybe it will be fixed one day.

**Comment by muffinresearch** [comment]
I'm going to close this since it's unlikely to be fixed if it hasn't in 9 years.
