### ISSUE TITLE
[Android] When the orientation of the device is changed the content of the page changes 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#451]
STR:
1. Load https://extensionworkshop-dev.allizom.org/ scroll down to a section on the Homepage. I tried with `Anatomy of an extension` or `Build extensions`. 
2. Change the orientation of the device 

Expected result:
The same place/line of text is shown as it was before changing orientation.

Actual result: 
The screen displays another line or even section of the page.

Notes:
This is reproducible on Android 8.0.0 
It's also reproducible on other sections of the site yet I find it more evident on the homepage.

Pixel - small screen (fron portrait to landscape)

![landing on small screens](https://user-images.githubusercontent.com/33448286/65513710-6f233980-dee4-11e9-9203-528d9beb4167.gif)

Huawei Tablet (from landscape to portrait)

![landing on homepage](https://user-images.githubusercontent.com/33448286/65513737-78aca180-dee4-11e9-84da-fcc6290e56d1.gif)

**Comment by muffinresearch** [comment]
Is this exclusive to this site, presumably this would happen on any website?

**Comment by ioanarusiczki** [comment]
@muffinresearch 
I don't see it reproducible on AMO or on [Download Firefox](https://www.mozilla.org/en-US/firefox/new/?utm_campaign=footer&utm_medium=referral&utm_source=addons.mozilla.org) Page with FF69 on Android 8.0 

I found a page I see it reproducible -[ Forum](https://discourse.mozilla.org/c/add-ons)  with FF69 on Android 8.0

**Comment by muffinresearch** [comment]
Yeah, I think it will depend completely on what a site adds / removes from the page and whether content above takes up more vertical space based on viewport width. As such I don't think this is something we can viably fix.
