### ISSUE TITLE
[Extension Basics] Create a link for "Overview of the Firefox extension features"

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#452]
Followup (as discussed with @caitmuenster on slack: #turtletown)
The "Overview of the Firefox extension features" from "Extension Basics" should be a link to “Cool Things Extensions Can Do” section on the landing page.

![Create a link](https://user-images.githubusercontent.com/33448286/65525839-ce8b4480-def8-11e9-8740-c616223fada7.png)

**Comment by rbrishabh** [comment]
Hey @championshuttler ! I am taking this one up.

**Comment by caitmuenster** [comment]
Hey @rbrishabh, thanks! Can you submit your patch by 25 September? Our code freeze starts on that date. If not, no worries -- we can find you another bug. :)

**Comment by rbrishabh** [comment]
Doing this right away @caitmuenster!

**Comment by ioanarusiczki** [comment]
@caitmuenster The URL redirects to "Why Create Extensions on Firefox" - the “Cool Things Extensions Can Do” is visible below (less visible on small devices).
Is that alright? 

The Desktop view 

![Extension Basics](https://user-images.githubusercontent.com/33448286/65668480-79f7de80-e04a-11e9-84cc-57fff4825503.gif)

The Android (small device) view 

![Pixel view](https://user-images.githubusercontent.com/33448286/65668645-c511f180-e04a-11e9-9a1e-58e388b307a6.gif)

**Comment by caitmuenster** [comment]
@ioanarusiczki Yes, this is fine. Thanks! :)

**Comment by ioanarusiczki** [comment]
@caitmuenster Ok, then this can be marked verified on dev with FF69(Win10&Android 8.0)
