### ISSUE TITLE
Links should be correct on extensions-basic page

### ISSUE THREAD

**Issue by championshuttler** [mozilla/extension-workshop#453]
Right now , all the links in Getting Started are linked to dev server, which is wrong. Needs to be fix

**Comment by AlexandraMoga** [comment]
@championshuttler are the links form the Extension Basics page the only ones affected?
Can we double check that there is no hardcoding in other Documentation pages as well?

**Comment by championshuttler** [comment]
@AlexandraMoga , I searched for the dev server link globally in the project, i did not find any other though :). Feel free to make sure once again.

**Comment by AlexandraMoga** [comment]
Verified fixed:

![image](https://user-images.githubusercontent.com/31961530/65574114-3bdcbb00-df75-11e9-8b5d-423ec0a4c2c7.png)
