### ISSUE TITLE
Page sections from Manage Overview don't have the same order as on the actual page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#474]
### Describe the problem and steps to reproduce it:
1. Open the 'Manage' documentation page - https://extensionworkshop.allizom.org/documentation/manage/
2. Scroll down slowly and follow the section markers in the Overview from the left side panel

### What happened?
The Overview doesn't follow the same order as the actual page - notice how the section marker jumps back and forth when you're scrolling 

### What did you expect to happen?
The Overview and the actual page should follow the same section order

### Anything else we should know?
- this reproduced both in -dev and stage (but I haven't notice it till now)

![2019-09-30_16-29-46](https://user-images.githubusercontent.com/31961530/65884907-57dfc280-e3a2-11e9-9aac-d37ed08031b1.gif)

**Comment by muffinresearch** [comment]
Fixed in https://github.com/mozilla/extension-workshop/pull/475

**Comment by muffinresearch** [comment]
This is still not working.

**Comment by muffinresearch** [comment]
This is fixed now on -dev.

**Comment by AlexandraMoga** [comment]
The Manage Overview order is correct now, both in -dev and stage.
