### ISSUE TITLE
The Developer newsletter subscription process is not very intuitive 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#476]
### Describe the problem and steps to reproduce it:
1. Open the Extension Workshop homepage
2. Scroll down to the footer section
3. Enter an email address in the Developer newsletter field and click on Sign up 
![image](https://user-images.githubusercontent.com/31961530/65947781-a2fce280-e441-11e9-8bce-e9d73de80548.png)

### What happened?
There are several issues:
1. After clicking on Sign up, you are immediately redirected to https://www.mozilla.org/en-US/newsletter/, without receiving a confirmation on the EW side that your subscription request was recorded (although in the page html there is a `newsletter_thanks` section dedicated for the subscription success message which should be displayed after clicking on Sign up)
2. If you check your inbox after this step, there is no confirmation email received for the Developer newsletter (@muffinresearch I believe this step depends on our integration with basket on -dev and stage, so in order to receive the email, basket should have received and processed our subscription request. Please correct me if I'm wrong)
3. By immediately redirecting the user to https://www.mozilla.org/en-US/newsletter/, where he is prompted again to fill in the email address to subscribe to the _general Mozilla_ newsletter, we are creating the impression that the subscription done on the EW side is not actually recorded. 
4. If the user Signs up again on https://www.mozilla.org/en-US/newsletter/, he will receive an email to confirm his details. After confirming the email, the user is redirected to his email preferences page. 
5. On the email preferences page, the user appears subscribed to general _Mozilla News_ , but not to the _Developer Newsletter_ : 

![image](https://user-images.githubusercontent.com/31961530/65950256-5ff13e00-e446-11e9-9740-b5739497551d.png)

### What did you expect to happen?
The user should be subscribed to the Developer newsletter only, since this is the option presented on the EW page.  After clicking on Sign up in EW, there should be a clear message that confirms his operation.  The additional subscription to the _Mozilla_ newsletter should be presented as an optional condition.

### Anything else we should know?
Ultimately, with the current process flow, the user has the option to subscribe to the developer newsletter on his email preferences page but this is not the expected use case.

**Comment by muffinresearch** [comment]
Hmm this seems to be a regression. I'm pretty sure this is all supposed to happen client-side and used to work that way. We have had issues before where this got broken when the form post url was changed. I'll investigate.

**Comment by muffinresearch** [comment]
Yep I think that's happened again, the `en-US` from the form URL has been removed.

**Comment by muffinresearch** [comment]
Regressed by https://github.com/mozilla/extension-workshop/pull/388

**Comment by muffinresearch** [comment]
This is fixed now on -dev.

**Comment by muffinresearch** [comment]
Fix is now on stage.

**Comment by AlexandraMoga** [comment]
@muffinresearch I've verified both -dev and stage and the subscription flow seems to work as expected now.
I'm adding the steps below, for future reference:

1. After filling in the subscription form on EW, the following message is displayed:
![image](https://user-images.githubusercontent.com/31961530/65969301-3566ab80-e46d-11e9-8709-5907e49efe2a.png)

2. After a few minutes, a confirmation email is received:

![image](https://user-images.githubusercontent.com/31961530/65969478-81195500-e46d-11e9-93cc-f91f607af0ce.png)


3. After clicking on 'Confirm' you are redirected to your email preference page, where the Add-ons Developer Newsletter is selected:
![image](https://user-images.githubusercontent.com/31961530/65969456-79f24700-e46d-11e9-85a8-a3bcd912eb58.png)

Marking the issue as verified fixed.

**Comment by muffinresearch** [comment]
@AlexandraMoga great, thanks very much for catching this.
