### ISSUE TITLE
Homepage - there are 2 blue links which redirect to the same page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#482]
@caitmuenster @muffinresearch Looks like I did not catch this last week: 

STR:
1. On homepage - https://extensionworkshop.com/ in the `Need some extra help along the way?` section there's: 
"Learn more about the community" 
"Learn about enhancing the API"

Actual result:
When clicked they both redirect to https://wiki.mozilla.org/Add-ons/Community/

Expected result:
Perhaps "Learn about enhancing the API" should redirect to another page.

Notes:
Reproducible on FF69 - Win10

![same URL](https://user-images.githubusercontent.com/33448286/66037890-4ff65e80-e519-11e9-8eee-11d5dff1e6aa.png)

**Comment by Patil2099** [comment]
@ioanarusiczki @muffinresearch Can I work on this issue?

**Comment by muffinresearch** [comment]
@Patil2099 not quite yet. We'll need to clarify where the link is supposed to point to.

**Comment by ruchikabgosain** [comment]
hey @muffinresearch I think it can probably redirect to : `https://wiki.mozilla.org/WebExtensions` what do you think?
