### ISSUE TITLE
about:debugging content needs to be updated 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#498]
@digitarald noted that `about:debugging` has changed dramatically and content needs to be updated accordingly.

**Comment by Rob--W** [comment]
This needs to be updated: https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

**Comment by muffinresearch** [comment]
@caitmuenster do you know who we should speak to, to provide the updated content?

**Comment by caitmuenster** [comment]
@rebloor Any chance you could take a look at this this week?

**Comment by rebloor** [comment]
@caitmuenster It is rather out of date! I'll start looking at this today and will have you a PR to review on Monday. OK?

**Comment by caitmuenster** [comment]
@rebloor Thank you! That sounds good.

**Comment by rebloor** [comment]
@caitmuenster see https://github.com/mozilla/extension-workshop/pull/538  A couple of observations:

- I was unable to reproduce the shadow border around the revised "reload" image, so have left it without a border. Are you aware of any instructions for adding the border? We should probably define a tool/border standard for the site to ensure consistency. Keeping it simple is probably best, either no border or maybe a simple line.
- I've re-created the videos, however, I'm not entirely convinced these are any more effective than including either a series of screenshots. an annotated screenshot, or combination of both as needed. The screenshot approach would also be somewhat easier to maintain. If you'd like me to do a version using screenshots and no videos, please let me know.

**Comment by caitmuenster** [comment]
Thank you @rebloor! 🙌🏼

> Are you aware of any instructions for adding the border? 

I am not. :( @muffinresearch might know? This is unfortunately beyond my current realm of knowledge. 

> If you'd like me to do a version using screenshots and no videos, please let me know.

Yes please! It's lower priority than the current batch of dev-doc-needed documentation, but I am +1 for making this documentation easier to keep updated in the future. :)
