### ISSUE TITLE
Landscape with browser chrome makes heading cramped on the homepage

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#503]
Using an Nexus 7 (Android) running FF Android, when the browser chrome is open it looks like this:

![Screen Shot 2019-10-10 at 16 43 12](https://user-images.githubusercontent.com/1514/66584713-8a957200-eb7d-11e9-8056-7bc0e23ff409.png)

We should add more space before the heading to allow for this.

**Comment by Patil2099** [comment]
@muffinresearch Can I work on this issue?

**Comment by muffinresearch** [comment]
@Patil2099 sure.

**Comment by muffinresearch** [comment]
Note: this is worse with the recent copy changes:

<img width="2560" alt="Extension_Workshop___Firefox_Extension_Workshop__Make_the_web_do_what_you_want__If_you_can_dream_it__our_open_souce_API_and_your_HTML__CSS__and_JavaScript_skills_can_make_it_happen_" src="https://user-images.githubusercontent.com/1514/66592203-7d33b400-eb8c-11e9-9fca-d7df6da28db8.png">
