### ISSUE TITLE
Investigate localization tooling under Jekyll

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#51]
As a follow-up to https://github.com/mozilla/extension-workshop/issues/46 let's setup localization tools so that this site can be localized.

**Comment by muffinresearch** [comment]
Here's a few things to investigate from https://github.com/planetjekyll/awesome-jekyll-plugins#multi-language--multi-lingual

- [**Language**](https://github.com/vwochnik/jekyll-language-plugin) ★23 (gem: [jekyll-language-plugin](https://rubygems.org/gems/jekyll-language-plugin)) by Vincent Wochnik -- multi-language plugin for posts, pages and includes
- [**Polyglot**](https://github.com/untra/polyglot) ★36 (gem: [`jekyll-polyglot`](https://rubygems.org/gems/jekyll-polyglot)) by Samuel Volin -- multi-lingual and I18n support tool
- [**i18n Tags**](https://github.com/KrzysiekJ/jekyll-i18n_tags) ★1 (gem: [jekyll-i18n_tags](https://rubygems.org/gems/jekyll-i18n_tags)) -- Translate your templates.
- [**Localization**](https://github.com/prometheus-ev/jekyll-localization) ★53 (gem: [jekyll-localization](https://rubygems.org/gems/jekyll-localization))  --  plugin that adds localization features to the rendering engine.
- [**Language**](https://github.com/vwochnik/jekyll-language-plugin) ★33 (gem: [jekyll-language-plugin](https://rubygems.org/gems/jekyll-language-plugin))  --  multi-language plugin for posts, pages and includes.

**Comment by caitmuenster** [comment]
One of the admins on the Jekyll support forum recommended https://jekyll-locale.netlify.com/. 

@muffinresearch, do you have any recommendations for how to evaluate these options? Or who should do it? :)

**Comment by muffinresearch** [comment]
> One of the admins on the Jekyll support forum recommended https://jekyll-locale.netlify.com/.
> 
> @muffinresearch, do you have any recommendations for how to evaluate these options? Or who should do it? :)

It really depends on what the translation requirements are.

Based on other sites we have localized we typically integrate with Pontoon, however doing that will likely have some constraints on what tools can be used to create localized versions of the pages. 

If we don't use Pontoon, who will be localizing the content? What languages are required?

**Comment by caitmuenster** [comment]
It would be great to integrate with with Pontoon, but it looks like they might not have the bandwidth until Q2/Q3 (see [Bug 1503683](https://bugzilla.mozilla.org/show_bug.cgi?id=1503683)). 

Based on last year's add-ons l10n campaign, we would want to target the following locales first: 
de, fr, es_ES, ru, pt_BR, zh_CN, pl, it, es_MX, ja, nl

@mconca, do you know if we have any budget to have these translated? I'm wondering if we should hire translators for a few of those locales (maybe the top 3 to start out with -- probably de, zh-CN, and ja). I'd also like to keep an option for the community to contribute translations.

**Comment by mconca** [comment]
@caitmuenster I wouldn't count on having any budget for translation this year.  If there is any budget left from the design and build of Phase 2, it will likely be used for promotion.

**Comment by caitmuenster** [comment]
Thanks @mconca! Ok, so we should plan to be dependent on the community for translations.

**Comment by muffinresearch** [comment]
Superceded by https://github.com/mozilla/extension-workshop/issues/665
