### ISSUE TITLE
Deprecated manifest key in self-hosted extension tutorial

### ISSUE THREAD

**Issue by mgunyho** [mozilla/extension-workshop#523]
The instructions on what to add to the extension manifest in [this tutorial](https://extensionworkshop.com/documentation/manage/updating-your-extension/#enable-update) are outdated. The manifest key `"applications"` should be `"browser_specific_settings"` instead, as described [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings).

**Comment by caitmuenster** [comment]
Thanks for filing this issue! Looks like this was fixed by #527.
