### ISSUE TITLE
Add "Get The Add-on" buttons to Promoting Your Extension page

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#563]
On the signed-in view of the [Developer Hub](https://addons.mozilla.org/developers/), we offer a link to a "Get The Add-on" button: 

![AMO Dev Hub - Get The Add-on button](https://user-images.githubusercontent.com/23342476/74861355-132bd800-52ff-11ea-9c26-d3b80510729f.png)

This link [directs to a post](https://blog.mozilla.org/addons/2015/11/10/promote-your-add-ons-with-the-get-the-add-on-button/) on the Add-ons Blog.

We should add these buttons to the `publish/promoting-your-extension/` page. 

Once that's done, we should file an issue on AMO to update the link to the section on the EW page.

**Comment by grlwholifts** [comment]
HI, i would like to take this up!

**Comment by caitmuenster** [comment]
So sorry @grlwholifts - this fell off my radar this week. :/ Here's what should happen: 

1) Add a new section to the promoting-your-extension.md file above the "Friends, family, and colleagues" section. This section will be titled "Promote your add-on from your website." 

2) Add a snazzy button to your website or blog telling people to "Get the add-on." We offer buttons in two sizes: 

**172 x 60 pixels**
[[insert this image](https://drive.google.com/open?id=1dzJF3h3Hm8VX0_4lpEUBaPx798pn5VoA)]  [note: add this file to the _assets/img/documentation/publish folder]

**129 x 45 pixels**
[[insert this image](https://drive.google.com/open?id=14MfFXkCoSRebCS5OcOT8GuMKrcb6GZah)]  [note: add this file to the _assets/img/documentation/publish folder]

Simply save these images, put them on your website, and link them to your add-on’s listing on [addons.mozilla.org](https://addons.mozilla.org). 

3. Make sure you update the `pages.yml` file to add the new section to the table of contents and sidebar

**Comment by grlwholifts** [comment]
Hi @caitmuenster no worries for the delay! I added the required changes. Let me know if they work 🦋
