### ISSUE TITLE
Redirect URLS without a slash to the slashed variant

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#568]
We should have only one version of each article. That should be fine once the canonicals are fixed as they point always to the `/` version but for example https://extensionworkshop.com/documentation/publish/submitting-an-add-on should redirect 301 to https://extensionworkshop.com/documentation/publish/submitting-an-add-on/ so we do not have split up backlinks counting for two urls as only one will be indexed.

**Comment by Romicodes** [comment]
@bobsilverberg  any chance I could pick this up for Outreachy  May 
2020

**Comment by bobsilverberg** [comment]
@Romicodes I'm not sure how appropriate this would be for a first contribution, but you can give it a try. I am about to disappear for two weeks, but you can ping @willdurand and/or @muffinresearch for direction and assistance.

**Comment by Romicodes** [comment]
@willdurand   getting ready to work on this for Outreachy May 2020 ! Could you please  point me in the right direction ?

**Comment by muffinresearch** [comment]
@Romicodes this issue probably isn't a good one because it will require configuration of s3 which is something that ops would need to handle.

**Comment by Romicodes** [comment]
@muffinresearch  could you please assign a good first issue to work on from the extension-workshop? Thanks much!

**Comment by Romicodes** [comment]
@bobsilverberg I did have a word with Stuart and  the redirect URL might not work because of the configuration of s3 which ops would need to handle. Could you please assign  a good first issue from the extension-workshop before you leave ? Thanks
