### ISSUE TITLE
Circle builds not running for a contributor's PR

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#577]
Historically we've had no issues with Circle running on PRS. But two branches for a contributor are stuck with the following message:

<img width="943" alt="Matrix_Room_Manifestation_by_grlwholifts_·_Pull_Request__571_·_mozilla_extension-workshop" src="https://user-images.githubusercontent.com/1514/76091656-e8f04080-5fb5-11ea-9c3c-ba240920b3da.png">

Here's an example of two branches that didn't fire a build:

- https://github.com/mozilla/extension-workshop/pull/571
- https://github.com/mozilla/extension-workshop/pull/569 (Merged) 

The only way I could get circle to build the latest rev was to push a PR of a copy of the same branch.

The webhooks for the PRs appear to have been fired OK. Also adding new commits didn't result in any change to the build status.

The earlier branch for #569 uses a branch called master so maybe that's related in some way? That said the remaining branch that is still stuck, isn't called master (but it does contain revisions that are from the previous branch).

/cc @bqbn

**Comment by bqbn** [comment]
I can't seem to be able to reproduce the issue. I filed a test PR https://github.com/mozilla/extension-workshop/pull/578, which trigger a build in CircleCI without problem (https://circleci.com/gh/mozilla/extension-workshop/tree/pull%2F578).

The github log shows the webhook for https://github.com/mozilla/extension-workshop/pull/571 was fired and received 200,

<img width="766" alt="Screen Shot 2020-03-06 at 3 26 43 PM" src="https://user-images.githubusercontent.com/2209111/76130272-18577b00-5fbf-11ea-8ba5-e1bdd9d867bc.png">

However I can't find a build for https://github.com/mozilla/extension-workshop/pull/571 in the CircleCI console.

Another piece of difference I notice is that for my PR, there were a few `status` calls to CircleCI after the initial `pull_request` call, whereas PR https://github.com/mozilla/extension-workshop/pull/571 only had the initial `pull_request` call, but no subsequent `status` calls.

**Comment by muffinresearch** [comment]
@bqbn would be interesting to try this again with an account with 0 permissions.

**Comment by muffinresearch-test** [comment]
See also https://github.com/mozilla/extension-workshop/pull/587

**Comment by muffinresearch-test** [comment]
See also https://github.com/mozilla/extension-workshop/pull/588 (branch is master)

**Comment by muffinresearch** [comment]
> I can't seem to be able to reproduce the issue. I filed a test PR #578, which trigger a build in CircleCI without problem (https://circleci.com/gh/mozilla/extension-workshop/tree/pull%2F578).
> 
> The github log shows the webhook for #571 was fired and received 200,
> 
> <img alt="Screen Shot 2020-03-06 at 3 26 43 PM" width="766" src="https://user-images.githubusercontent.com/2209111/76130272-18577b00-5fbf-11ea-8ba5-e1bdd9d867bc.png">
> 
> However I can't find a build for #571 in the CircleCI console.
> 
> Another piece of difference I notice is that for my PR, there were a few `status` calls to CircleCI after the initial `pull_request` call, whereas PR #571 only had the initial `pull_request` call, but no subsequent `status` calls.

@bqbn I concur with not being able to repro. I think we can just close this out and see if it comes up again.
