### ISSUE TITLE
Shorten all other page titles to less than 70 characters 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#584]
Note: this issue is probably not appropriate for contributors at this time. 

Shortening all page titles to less than 70 characters will help with SEO. This is related to #582. 

Before this issue can be fixed, we probably need to supply the 70 character or less titles for all pages. 

I think this can be fixed by updating the 'title' line in each .md file: 

![Screen Shot 2020-03-09 at 10 23 10 AM](https://user-images.githubusercontent.com/23342476/76240172-04df2680-61f0-11ea-8c2b-a7c39a9030b6.png)

@muffinresearch, is that right?

**Comment by muffinresearch** [comment]
This should have a test that looks at the yaml and validates it when this is fixed.

**Comment by muffinresearch** [comment]
The test added in #680 covers this from the perspective of the titles coming from frontmatter. I'm not sure we need to go much further than this.

https://github.com/mozilla/extension-workshop/blob/445670542d9e2da99f46f7aeb765a247322539f6/tests/frontmatter.test.js#L8-L14
