### ISSUE TITLE
Feed import is broken

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#589]
The feed can't be loaded due to missing CORS headers on the feed endpoint. 

FF shows this in the console: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://blog.mozilla.org/addons/feed/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

```bash
curl -I https://blog.mozilla.org/addons/feed/
HTTP/2 200
server: nginx
date: Thu, 12 Mar 2020 12:15:43 GMT
content-type: application/rss+xml; charset=UTF-8
vary: Accept-Encoding
vary: Accept-Encoding
x-xss-protection: 1; mode=block
last-modified: Wed, 11 Mar 2020 15:50:35 GMT
etag: "2d3ca91f9c7b3bfbf72e4cf48418efb4"
link: <https://blog.mozilla.org/addons/wp-json/>; rel="https://api.w.org/"
x-powered-by: WP Engine
x-frame-options: SAMEORIGIN
x-cacheable: NO:Passed
cache-control: max-age=0, must-revalidate, private
x-cache: MISS
x-pass-why: special path
accept-ranges: bytes
```

To fix this we'd need CORS headers to be added to the feed endpoint. This would have previously been there because this worked in the past.

**Comment by muffinresearch** [comment]
@bqbn is this something ops can help with or is there someone else we should point this to?

**Comment by bqbn** [comment]
`https://blog.mozilla.org/` is managed by IT. We can probably [file a bugzilla ticket](https://bugzilla.mozilla.org/enter_bug.cgi?product=Websites) to have it addressed. I was told Corey's team manages it.

**Comment by muffinresearch** [comment]
Thanks @bqbn, I've filed an issue at https://bugzilla.mozilla.org/show_bug.cgi?id=1625119

**Comment by muffinresearch** [comment]
This was fixed in the feed URL.
