### ISSUE TITLE
Change site name to Firefox Extension Workshop 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#592]
To help improve SEO, we're renaming this site to Firefox Extension Workshop. 

For this issue, we need to update: 

- Header bar: 
![Screen Shot 2020-03-17 at 9 14 03 AM](https://user-images.githubusercontent.com/23342476/76876820-b6eda280-682f-11ea-9514-8b62b1a13779.png) (be sure to check how this formats) 

- The site title in `config.yml`

**Comment by obviyus** [comment]
I’d like to take this up!

**Comment by caitmuenster** [comment]
Go for it @obviyus!
