### ISSUE TITLE
Update references of Extension Workshop to Firefox Extension Workshop

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#593]
Related to #592. To improve SEO, we are updating the name of this site to Firefox Extension Workshop. 

For this issue, we need to: 

- Find all instances in the content of this site where we refer to it as Extension Workshop 
- Update those instances to be Firefox Extension Workshop

**Comment by obviyus** [comment]
Having just worked on #592, this would be a great issue to continue my work with. Can I get assigned to it?

**Comment by caitmuenster** [comment]
Hey @obviyus, thanks for your interest! Would it be ok if you wait for a day or two to see if anyone else is interested in working on this?

**Comment by obviyus** [comment]
Sure!

**Comment by championshuttler** [comment]
Hey @obviyus thanks for the interest but we are little short on good first bugs so please wait if someone else is interested :)

**Comment by AyahRamahi** [comment]
Hello 😄 I am an Outreachy 2020 applicant, can I work on this issue?

**Comment by caitmuenster** [comment]
Hey @AyahRamahi, go for it!
