### ISSUE TITLE
Homepage content updates - use the word "add-on" more

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#594]
To help improve SEO, we need to be a little bit more liberal with our use of the word "add-on" on Firefox Extension Workshop. 

We can start by making the following content changes on the homepage: 

- Update "Get help creating and publishing Firefox extensions that make browsing smarter, safer, and faster." to "Get help creating and publishing Firefox add-ons that make browsing smarter, safer, and faster."

- Change "Cool Things Extensions Can Do" to "Cool Things Add-ons Can Do"

- Change "Firefox extensions are built using the WebExtensions API, so your creation will be accessible to users no matter what browser they use." to "Firefox add-ons are built using the WebExtensions API, so your creation will be accessible to users no matter what browser they use."

- Update "When you build on Firefox, you build with a community of extension developers" to "When you build on Firefox, you build with a community of add-on developers"

**Comment by xlisachan** [comment]
@caitmuenster, can I work on this?

**Comment by caitmuenster** [comment]
Hi @xlisachan, go ahead! We'll formally assign you when you submit a PR.
