### ISSUE TITLE
Update content on Add-ons for desktop apps 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#599]
[Support for sideloading has ended with Firefox 74. ](https://blog.mozilla.org/addons/2020/03/10/support-for-extension-sideloading-has-ended/) The content for this page needs to be updated. Once you have updated the text based on the copy below, be sure you update the lines for `contributors`, `last_updated_by`, and `date`. 

You can find the template for the alert module in the `sidebar-master-template.md` file. 

_____

[alert module] Starting with Firefox 74, it is no longer be possible to have an extension be automatically installed as part of another application install. See the [Add-ons Blog](https://blog.mozilla.org/addons/2020/03/10/support-for-extension-sideloading-has-ended/) for more information. [/alert]

If you have developed an add-on to complement a desktop application, you will need to provide a way for users to install your extension. You can direct the user to install the add-on from your website or list it on addons.mozilla.org (AMO). 

Of these options, directing the user to install from AMO is recommended. It avoids any issues with the installation process; the user will not get an interstitial messages during the installation of the add-on, find the add-on installed but disabled, or find that the add-on was not installed.

If you would like to direct users to install the add-on from your website, please read this article on [self-distribution](https://extensionworkshop.com/documentation/publish/submitting-an-add-on/#self-distribution) to learn how to prepare the .xpi file for web installs. 

Enterprise administrators and people who distribute their own builds of Firefox (such as some Linux and Selenium distributions) will be able to continue to deploy extensions to users. Enterprise administrators can do this via [policies](https://github.com/mozilla/policy-templates#extensionsettings). Additionally, Firefox Extended Support Release (ESR) will continue to support sideloading as an extension installation method.

**Comment by ani-sha** [comment]
@caitmuenster I would like to work on this.

**Comment by caitmuenster** [comment]
Go for it @ani-sha!
