### ISSUE TITLE
Update content for Self Distribution Options 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#600]
In the `self-distribution` file, we need to update the content for self-distribution options. Updated text is below: 
____

When you choose to distribute an add-on yourself, they can be installed using the following methods:

* Web download (link to `/documentation/publish/submitting-an-add-on/#self-distribution`)—make your extension available on a suitable web accessible server and when the user downloads the signed add-on file Firefox will install it.
*  Installing add-on from file (link target remains the same)—enables a user to install an add-on using an .xpi file saved on their computer.
* Add-ons for use with a desktop app—starting with Firefox 74, it is no longer be possible to have an extension be automatically installed as part of another application install. See the [Add-ons Blog](https://blog.mozilla.org/addons/2020/03/10/support-for-extension-sideloading-has-ended/) for more information.
* Add-ons in an enterprise environment—this page discusses the use of signed compared to unsigned extensions, installation options, the Firefox settings affecting installation, and including add-ons with a custom Firefox install package.

**Comment by piculet** [comment]
Hi @caitmuenster I'd like to give a shot to this issue, I am an outreachy applicant.

**Comment by championshuttler** [comment]
Go for it. Thanks

**Comment by piculet** [comment]
@championshuttler Do i need to remove the links from `Add-ons for use with a desktop app` and `Add-ons in an enterprise environment` or retain the previous links ?

**Comment by championshuttler** [comment]
> @championshuttler Do i need to remove the links from `Add-ons for use with a desktop app` and `Add-ons in an enterprise environment` or retain the previous links ?

I think those links need to be removed as you did in PR , @caitmuenster can you please confirm it once

**Comment by caitmuenster** [comment]
Commented on the PR. Link to Add-ons in the enterprise environment should remain. Sorry for overlooking that!

**Comment by caitmuenster** [comment]
Closed by #603
