### ISSUE TITLE
Update content on Publish Overview page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#601]
In the "Distribute your signed extension" on the Publish overview page, the following changes need to be made: 

- Edit "Provide a download location for the signed extension file for users to self-install or sideload into Firefox." to "Provide a download location for the signed extension file for users to self-install into Firefox." 

- Remove "Include the extension installation as part of the installation of a desktop application."

**Comment by apsychogirl** [comment]
Hi, Can I take this up?

**Comment by championshuttler** [comment]
Go for it. Thanks

**Comment by caitmuenster** [comment]
Closed by #605
