### ISSUE TITLE
Change instances of webextensions.tech to webextensions.in

### ISSUE THREAD

**Issue by championshuttler** [mozilla/extension-workshop#608]
Domain got expire , we needed to migrate to new domain name

The tool is migrated to https://webextensions.in

Change all the instances of webextensions.tech to webextensions.in

**Comment by ani-sha** [comment]
@caitmuenster I would like to take this.

**Comment by championshuttler** [comment]
Go for it @ani-sha , Thanks!

**Comment by ani-sha** [comment]
@championshuttler should I update the details of contributors, last modified date and time too?

**Comment by championshuttler** [comment]
@ani-sha yes please
