### ISSUE TITLE
Tracking protection is blocking the youtube related cookies

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#61]
If tracking protection is on you see:

```
Request to access cookie or storage on “https://www.youtube.com/iframe_api” was blocked because it came from a tracker and content blocking is enabled.
```

**Comment by muffinresearch** [comment]
@caitmuenster I think we can just close this out it's just warnings from the tracking protection doing its job - what do you think?

**Comment by caitmuenster** [comment]
Oh yeah, if it's just tracking protection doing its job we can close this out. 

Thanks!
