### ISSUE TITLE
package-your-extension: update zip command

### ISSUE THREAD

**Issue by mickro** [mozilla/extension-workshop#624]
### Describe the problem and steps to reproduce it:

There is a wrong `zip` command
https://extensionworkshop.com/documentation/publish/package-your-extension/

> ZIP the content of the directory—remembering to excludes those files that aren’t needed to run the > extension, such as .git, graphic sources, and similar files—using the command `zip -r -FS ../my-extension.zip * --exclude *.git*`.

### What happened?

The command didn't worked out of the box.

### What did you expect to happen?

It would be nicer that work by copy / paste.

### Anything else we should know?

Easily fixavble by replacing the command as following:
```diff
-  zip -r -FS ../my-extension.zip * --exclude *.git*
+  zip -r -FS ../my-extension.zip * --exclude .git
```

**Comment by willdurand** [comment]
Hiii Mickael! It's been a long time 😉 



> Easily fixavble by replacing the command as following:
> 
> ```diff
> -  zip -r -FS ../my-extension.zip * --exclude *.git*
> +  zip -r -FS ../my-extension.zip * --exclude .git
> ```

Would `--exclude '*.git*'` (with the single quotes) work for you? I think we intended to use wildcards to ignore other git files. If that works, would you like to contribute by submitting a PR? Thanks!

**Comment by mickro** [comment]
Hey Willam ! As Moziila worker. nice :)

Else yes `--exclude '*.git*'` works well. I can do a PR for this.

thanks!
