### ISSUE TITLE
Link to "download location for the signed extension file" points to wrong page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#631]
On the Publish overview, the link for "download location for signed extension" file currently points to the Sideloading page. It should point to the [self-distribution](https://extensionworkshop.com/documentation/publish/self-distribution/) page. 

![Screen Shot 2020-05-05 at 9 41 40 AM](https://user-images.githubusercontent.com/23342476/81091946-c34bbe80-8eb4-11ea-9d3e-9cb4187c9f97.png)

**Comment by soniasingla** [comment]
Hi Caitlin

Can you assign me this bug? :)

**Comment by caitmuenster** [comment]
Hi @soniasingla! Go ahead and start working on this! We'll assign it to you once a PR is up. 👍
