### ISSUE TITLE
Update enterprise add-on documentation

### ISSUE THREAD

**Issue by mkaply** [mozilla/extension-workshop#647]
We should update the docs here:

https://extensionworkshop.com/documentation/enterprise/enterprise-distribution/

to remove sideloading.

And probably move some of the content from here:

https://extensionworkshop.com/documentation/enterprise/enterprise-policies-that-impact-extensions/#relevant-policies

onto the first page/.

We should cover installing extensions using the distribution directory and we should remove all the scopes stuff.

(I'll help write)

**Comment by bjherbison** [comment]
Search this page for "Howto not document a feature" for complaints about the current documentation. ("Lets hope that eventually Mozilla will write some decent documentation for this new feature.")
https://klaus-hartnegg.de/gpo/2018-05-26-Firefox-Policies.html

**Comment by mkaply** [comment]
Ouch that hurts. You know I'm the person that writes all that documentation. And I even know Klaus.

I'll see what I can do to make things more concise.

**Comment by caitmuenster** [comment]
Heads up @mkaply, I'm going to ask you to review the PR for this. :)

**Comment by mkaply** [comment]
Of course, and let me know if you want to work together on it.
