### ISSUE TITLE
Edit link to contribute on GitHub

### ISSUE THREAD

**Issue by rugk** [mozilla/extension-workshop#656]
IMHO you miss an "Edit this site on GitHub" link or so on your site that directs me to the exact source for the page that is currently open.

I see people who edited it and that points to GitHub. That was the only hint for me to **manually* search GitHub to find the repo + manually search the correct file.

Quite cumbersome…

An "Edit this here" link would make it way more easier.

**Comment by muffinresearch** [comment]
Yep this is a good call, this will be fixed in #654

**Comment by muffinresearch** [comment]
Patch is here https://github.com/muffinresearch/extension-workshop/commit/142f4b000b6514a8d57b3bdeb37efab7ba17a5d8

**Comment by muffinresearch** [comment]
This was fixed in #654, which is on the [-dev site](https://extensionworkshop-dev.allizom.org/) but not yet released to production.

![Manage___Firefox_Extension_Workshop](https://user-images.githubusercontent.com/1514/87828749-7fdadc80-c875-11ea-91dc-b4038594f0c7.jpg)
