### ISSUE TITLE
Clean-up broken links

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#679]
Running a link checker has shown up a bunch of broken links on the site:

- https://developer.mozilla.org/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE from /documentation/develop/differences-between-desktop-and-android-extensions/
- https://developer.mozilla.org/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE#Enable_remote_debugging_in_Firefox_for_Android from /documentation/develop/developing-extensions-for-firefox-for-android/
- https://developer.mozilla.org/docs/browser_specific_settings from /documentation/develop/test-permission-requests/ (2 cases)

17 Github username links across 55 instances:

- https://github.com/mdnwebdocs-bot
- https://github.com/hatem45
- https://github.com/david_ross
- https://github.com/potterwrit
- https://github.com/andymckay-github
- https://github.com/V@no
- https://github.com/hasangol
- https://github.com/Cikgu77
- https://github.com/01787500664
- https://github.com/tedmcox
- https://github.com/iwanrezpect
- https://github.com/gray_-_wolf
- https://github.com/Leif-AMO
- https://github.com/johnadungan
- https://github.com/PikadudeNo1
- https://github.com/niharikak101
- https://github.com/Zearin_Galaurum

**Comment by Abjtkr05** [comment]
i want to work on the issue

**Comment by muffinresearch** [comment]
@caitmuenster what do you think about un-linking the github usernames?

**Comment by Yashs911** [comment]
Hi, @muffinresearch I would like to work on this issue. Can you elaborate on what all changes do I need to make?

**Comment by caitmuenster** [comment]
Hi @Yashs911! You will need to replace the broken links on the pages @muffinresearch listed above with valid links. I've listed the valid links [here](https://docs.google.com/document/d/10H3kfUC_c-04kPTCFV9G3ZUJxFNi3raQe1yXZB5pDog/edit#heading=h.qxz8872buikx). 

Don't worry about replacing broken links to Github users. :) 

Once you submit a PR, we'll assign you to the issue. 

Let us know if there are any questions!

**Comment by Yashs911** [comment]
@caitmuenster I have created a PR.
