### ISSUE TITLE
Unify link display between search and tag pages

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#713]
Split out from #703 

Tag results currently look like this (from https://extensionworkshop.allizom.org/tags/guide/)

<img width="1699" alt="Results_for_tag__guide____Firefox_Extension_Workshop" src="https://user-images.githubusercontent.com/1514/89524864-34b14b00-d7dd-11ea-9ba3-3b8e0817f308.png">

Search results look like this (from https://extensionworkshop.allizom.org/search-results/?q=guide):

<img width="1773" alt="Search_Results___Firefox_Extension_Workshop" src="https://user-images.githubusercontent.com/1514/89524920-4db9fc00-d7dd-11ea-8797-0b06d0cc3d23.png">

To unify the results the following changes are required: 

* Remove the hostname from the search results
* Add the number of results to tag results.
* Remove the list item number from tag results.

**Comment by vcarciu** [comment]
Verified as fixed : 
![guide tag](https://user-images.githubusercontent.com/1583842/89638536-aad4b100-d8b4-11ea-82ec-5769b3504e37.gif)
