### ISSUE TITLE
[MOBILE] Carousel boxes are different sizes on Homepage 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/extension-workshop#718]
Steps to reproduce:

1.On an Android device access https://extensionworkshop.allizom.org/.
2.Observe and browse through the carousels from “Cool Things Add-ons Can Do” and “Latest Developer News” section.

Expected result:
The boxes are the same size.

Actual result:
The boxes are different sizes.

Notes:
Not reproduced on the Production site.

Please see video for this issue :
![20200805_161018](https://user-images.githubusercontent.com/1583842/89635999-9393c480-d8b0-11ea-8ea0-7fa072dcd356.gif)

**Comment by muffinresearch** [comment]
Great catch. This turned out to be caused by the non-minified file in the package being an old version of the lib.

**Comment by vcarciu** [comment]
Verified as fixed: 


![ewcarousel](https://user-images.githubusercontent.com/1583842/89911930-aaad1c00-dbfa-11ea-97bc-e408bec1e6a2.gif)
