### ISSUE TITLE
CSP needs review

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#8]
```
default-src 'self'; 
font-src 'self' fonts.gstatic.com use.typekit.net; 
form-action 'none'; 
frame-ancestors 'self';
img-src 'self' data: https://ssl.google-analytics.com https://www.google-analytics.com https://p.typekit.net/p.gif; 
object-src 'none';
script-src 'self' 'unsafe-inline' use.typekit.net https://ssl.google-analytics.com https://www.google-analytics.com/analytics.js;
style-src 'self' 'unsafe-inline' fonts.googleapis.com; frame-src 'none';
```
Few things that stand-out at a glance:

- `form-action: 'none'` will probably prevent the newsletter form from working.
- `base-uri` should be defined.
- Doe the site need to frame itself? Maybe frame-ancestors could be 'none'
- Can `default-src` be `'none'` that's a tighter default.
- Does script-src need to allow `'unsafe-inline'`? That weakens the CSP considerably.

**Comment by caitmuenster** [comment]
@muffinresearch How's it going with this issue? Anything we can do to help?

**Comment by muffinresearch** [comment]
I've already re-configured it quite a bit, so most of this should be addressed already.

The GA settings could all be removed until we have GA configured and base-uri still could be defined.

@psiinon I wouldn't mind if you gave this a look too as a sanity check.

**Comment by psiinon** [comment]
Will do!

**Comment by psiinon** [comment]
Yeah, looking good with the new spaces.

**Comment by muffinresearch** [comment]
CSP was missing from statics, so I've just added that plus, `X-frame-options` and `referrer-policy`.

**Comment by muffinresearch** [comment]
@psiinon unless you can spot anything else needed here, I think we can close this out.

**Comment by psiinon** [comment]
Thats looking good to me
