### ISSUE TITLE
Content guideline side-bar button + links need updating

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#80]
These links on the sidebar don't link anywhere obvious - I presume they're placeholders that need updating.

![master_template___extension_workshop](https://user-images.githubusercontent.com/1514/52495879-d399be80-2bc9-11e9-919b-f15d3dbd5cc9.jpg)

**Comment by caitmuenster** [comment]
Tagging @MeridelW here. I think they were going to link back into the Dev Hub so developers could edit their product page.

**Comment by muffinresearch** [comment]
> Tagging @MeridelW here. I think they were going to link back into the Dev Hub so developers could edit their product page.

Ah makes sense, so the button can probably link to https://addons.mozilla.org/developers/addons

**Comment by caitmuenster** [comment]
Link to "Edit Product Page" has been updated. 

Site feedback can go to https://github.com/mozilla/extension-workshop/issues. 

Privacy policy can go to https://www.mozilla.org/privacy/websites/  (I think; please correct me if I'm wrong!) 

@muffinresearch, I'm not sure where "Changelog" should link to. Can you advise?

**Comment by muffinresearch** [comment]
> Link to "Edit Product Page" has been updated.
> 
> Site feedback can go to https://github.com/mozilla/extension-workshop/issues.
> 
> Privacy policy can go to https://www.mozilla.org/privacy/websites/ (I think; please correct me if I'm wrong!)
> 
> @muffinresearch, I'm not sure where "Changelog" should link to. Can you advise?

No changelog exists, so unless one is going to be created I think this can be removed.

**Comment by caitmuenster** [comment]
That works for me. @MeridelW, is it ok if the changelog is removed?
