### ISSUE TITLE
Clean up movie section of content guidelines master template 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#88]
content-guidelines/master-template/ is a bit of a mess at the moment -- there is an untitled movie in the middle of the page with two smaller duplicate movies below. 

![screen shot 2019-02-11 at 10 41 18 am](https://user-images.githubusercontent.com/23342476/52585593-09b58900-2dea-11e9-9098-8b28c2969559.png)

@MeridelW, how do you want this to look?

**Comment by caitmuenster** [comment]
We should probably also clean up all of the other "lorem ipsums" in the Heading One, Do's & Don'ts, Requirements, and Stuck? Try This sections.

**Comment by MeridelW** [comment]
Yes, I need to clean this up, and add the other pages. 

I am meeting with Stuart on Wednesday for a tutorial on how to do this. I had met with Lance but unfortunately the way he and I had planned to go about this isn't working.

**Comment by lancecummings** [comment]
Let me know if you need my input on any of this.

**Comment by muffinresearch** [comment]
Isn't the master template just a grab bag of style options and UI? If so maybe we should consider updating the site to either not link to the master template (probably a `hidden: true` flag mechanism could be added for this) or separately make some changes to only publish it locally.

**Comment by MeridelW** [comment]
I'm having trouble finding the link to the new repo for the content guidelines (I have the old broken one). @muffinresearch Can you please share with me when get a chance? Thank you!

**Comment by MeridelW** [comment]
I am all set, thanks!

**Comment by muffinresearch** [comment]
I think there's no further actions needed here, so I'm going to close this out on the basis that the template is just a set of examples, it's not supposed to stand-up as content on its own.
